### ISSUE TITLE
SEGV sur `cat /dev/random | ./42sh`

### ISSUE THREAD

**Issue by dkrmr** [itheof/42sh-posix#100]
Voir: https://ftsh.slack.com/files/rcargou/F3TGBLB88/screen_shot_2017-01-20_at_1.46.51_pm.png

**Comment by tmielcza** [comment]
C'aurait été sympa de préciser quelle commande à été exécutée, sur quelle branche, etc.

**Comment by dkrmr** [comment]
Voir avec @Otaekek

**Comment by tmielcza** [comment]
Si on en trouve d'autres, on refera des issues.
