### ISSUE TITLE
Module Builtins

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#104]
Interface du module builtins:
```c
// interface d'un builtin
int builtin_<name>(int argc, const char * const *argv);

// pour savoir si une commande est un builtin
bool is_a_builtin(const char *cmd);

// renvoie -1 si le builtin n'existe pas, ou la valeur de retour s'il a été exécuté
int exec_builtin(const char *cmd, int argv, const char * const *argv);
```

Les builtins à faire:
```c
int builtin_cd(int argc, const char * const *argv);
int builtin_echo(int argc, const char * const *argv);
int builtin_env(int argc, const char * const *argv);
int builtin_setenv(int argc, const char * const *argv);
int builtin_unsetenv(int argc, const char * const *argv);
int builtin_exit(int argc, const char * const *argv); // c'est un special builtin mais baste
// int builtin_help(int argc, const char * const *argv); // ?
// int builtin_read(int argc, const char * const *argv); // ce serait sympa de l'avoir puisqu'on gère déjà les descripteurs de fichiers
```

Question : Comment va se passer l'environnement aux builtins ?

**Comment by itheof** [comment]
L'environnement est accesible aux builtins via les routines du module variable. Sinon je pense que `is_builtin` est mieux comme nom.

**Comment by dkrmr** [comment]
En fait, pourquoi le proto est `(int argc, const char * const *argv)` ?
Pourquoi ne pas envoyer un simple `t_array` ?
`argc == array.len`
`argv == array.data`

**Comment by itheof** [comment]
l'idee de base etait de rester coherent avec les args qu'on recoit dans un prog quand on l'exec. De plus a travers le t_array on perd le `const` qui me semble vraiment important.

**Comment by dkrmr** [comment]
Si tu pouvais changer le proto en `bool is_builtin(const char *cmd, size_t len);` ce serait super. Ça m'éviterai de `strsub` le nom de la commande à partir de l'input.

**Comment by tmielcza** [comment]
Il y en a des bouts deja merge, d'autres dans la branche exec. L'issue sera fermee avec le merge de l'execution.

**Comment by tmielcza** [comment]
... C'est à dire il y a quelques jours. Allez, zou!
