### ISSUE TITLE
Repo github

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#112]
Quand on regarde les contributions des membres du projet selon github, on se rend compte qu'il n'y figure meme pas @Otaekek et que @Kerollmops est un des plus presents alors qu'il ne participe plus depuis des mois.
C'est du entre autres aux squash des merges qui font que @dkrmr reccupere tous les honneurs.

Je trouve ca injuste.
Et blague a part c'est pas cool qu'un des membres les plus productifs n'apparaisse meme pas. Deja pour le concours de kiki, et aussi quand on considere que le projet peut etre vu de l'exterieur, notamment s'il apparait sur un CV.
Alors bon, de toutes facons chacun va fork pour avoir un repo a son nom et edit l'historique pour pretendre avoir tout fait (mentez pas je vous connais) mais ca fait pas vraiment serieux.

Bon je sais pas si c'est une vraie "issue", mais en tous cas j'y pense depuis quelques jours et je me dis que si on pouvait se demerder pour que les contributeurs apparaissent correctement, quitte a ne plus squash, ce serait cool.

**Comment by itheof** [comment]
Github ne montre dans les collaborateurs que les membres de Github. Pour ca il match l'adresse e-mail du commit avec sa base de donnees. Pour apparaitre dans l'historique, il suffit qu'il rajoute l'e-mail avec lequel il a commit dans son compte Github.

**Comment by tmielcza** [comment]
Alors, oui, mais non.
Soit, Rodolphe est une bite, mais le fait de merge en squashant les commits, fait de la personne qui merge l'auteur de tout le code du nouveau commit, donc il y a selon moi toujours un probleme (c'est pas pour dire mais actuellement pour la master de github c'est Donovan qui a fait le lexer, par exemple).

**Comment by tmielcza** [comment]
Alors, oui, mais non.
Soit, Rodolphe est une bite, mais le fait de merge en squashant les commits, fait de la personne qui merge l'auteur de tout le code du nouveau commit, donc il y a selon moi toujours un probleme (c'est pas pour dire mais actuellement pour la master de github c'est Donovan qui a fait le lexer, par exemple).

**Comment by itheof** [comment]
Bah y a pas trop de solutions a ca. Si on veut squash en un commit, y'a qu'un auteur.
T'es jaloux, c'est tout.

**Comment by tmielcza** [comment]
> tmielcza committed with dkrmr 21 days ago

Apparemment c'est possible d'avoir deux auteurs pour un commit. On n'est pas oblige de passer par github pour faire les squash de toutes manieres.
Je suis pas jaloux dans le sens ou je ne convoite pas de "voler" le travail de mes collegues, mais par contre ca me fait un peu chier bien evidemment, sinon j'en parlerais pas.
Et comme je l'ai deja dit, j'ai rien contre le fait de pas squash si ca peut permettre que chacun puisse voir et montrer le travail qu'il a fourni sur ce projet.

**Comment by dkrmr** [comment]
Quel comportement vous voulez adopter ? On squash en local uniquement ?

**Comment by tmielcza** [comment]
Si ca peut permettre de conserver les auteurs, oui.

**Comment by dkrmr** [comment]
Ca me va.

**Comment by tmielcza** [comment]
Et franchement je serais chaud pour reprendre toute la branche master et refaire les merges proprement. Si tu veux bien m'aider :3

**Comment by dkrmr** [comment]
Heu... ca va etre long...

**Comment by tmielcza** [comment]
On commence quand tu veux (Pas maintenant, je suis pas la)

**Comment by tmielcza** [comment]
J'ai edit l'issue #7
