### ISSUE TITLE
SEGFAULT

### ISSUE THREAD

**Issue by Otaekek** [itheof/42sh-posix#114]
![screen shot 2017-02-08 at 3 20 24 pm](https://cloud.githubusercontent.com/assets/8776538/22741054/2ca0a0cc-ee12-11e6-94d9-3508f11bb43a.png)

cat /dev/urandom > e
cat e | ./42sh
Branch: master
Precision: ce n'est pas le meme probleme qui celui de l'autre issue. enfin peut etre que si.

**Comment by tmielcza** [comment]
De memoire ca ne pete pas au meme endroit ? En tous cas c'est un probleme. On est dessus avec @dkrmr.

**Comment by Otaekek** [comment]
Essayer de recuperer l'input sans passer par l'UI. Ca vient peut etre de la.

**Comment by dkrmr** [comment]
Ce n'est pas la branch `master`. C'est `new_main` (puisque je vois `shell_loop` dans la backtrace).

**Comment by dkrmr** [comment]
![screen shot 2017-02-08 at 3 44 51 pm](https://cloud.githubusercontent.com/assets/16935834/22742023/99b09e6c-ee15-11e6-8911-5cf5389525c2.png)

J'ai produit un cas particulier aussi. Apparemment le lexer peut renvoyer un tableau de token vide (ce qui ne pouvait pas arriver avant avec l'UI)

**Comment by tmielcza** [comment]
Pendant un instant j'ai cru que tu disais que le lexer plantait, mais en fait c'est la faute de l'UI ;P

**Comment by dkrmr** [comment]
Ce n'est pas la faute de l'UI, ni du lexer. C'est juste un cas qu'on a prévu ne jamais arriver, c'est pour ça qu'il y a un `assert`, et qui finalement se produit.

**Comment by tmielcza** [comment]
Je ferme cette issue, a partir de maintenant (enfin il faut le faire depuis le debut) ce serait pas mal de report les bugs au fur et a mesure dans des issues dediees, explicites, et qui donnent des indications precises quand a comment les reproduire.
