### ISSUE TITLE
Builtin History

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#117]
# Introduction
Sous *mksh* (notre shell de référence), la builtin `history` n'est autre que ceci:
```
$ type history
history is an alias for '\builtin fc -l'
```
Voilà ce que POSIX a à nous dire au sujet des options de `fc -l`:
`fc -l [-nr] [first [last]]`

Donc notre builtin `history` sera invoquée avec les options suivantes:

### `history [-nr] [first [last]]`

# Développement
Les actions de la builtin `history` sont les suivantes :
* Sans argument, elle liste l'historique de `first` a `last`, une commande par ligne, en précédant chaque commande de son index. Si `last` n'est pas donné, on considère qu'il s'agit de la commande la plus récente de l'historique, et si `first` n'est pas donné non plus on liste tout l'historique.
* L'option `n` permet de lister l'historique sans afficher les indexes.
* L'option `r` permet de lister l'historique en sens inverse (même comportement qu'en intervertissant `first` et `last`)

`first` et `last` peuvent être :
* `[+]number`, un index absolu dans l'historique.
* `-number`, un index relatif à la dernière commande (dont l'index relatif est -1).
* `string`, la commande la plus récente commençant par `string`.

**Comment by dkrmr** [comment]
Ca me semble clair, bon travail !
