### ISSUE TITLE
Fix new main

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#121]
### /!\\ Attention cette issue n'a aucun sens

Pour ceux que ca interesse (moi par exemple) voici (selon moi) la liste des choses a fix sur le new main :

- [x] Mettre des <errno.h>
- [x] Renvoyer 0 si EOF + string vide
- [x] Rebase sur master
- [ ] Si isatty() fail, retourner une erreur (?)
- [x] sizeof() des variables plutot que des types
- [ ] Commenter (notamment la boucle d'initialisation des termcap)
- [x] Virer des commentaires
- [ ] Écrire des tests
- [ ] Tester en lancant dans un programme qui pourrit les termcap (Dites moi que ca sert a rien si vous voulez, j'ai pas confiance)
- [x] Le retour de read dans ui_loop est check mais n'entraine jamais une erreur (**infinite loop**)
- [x] Verifier que la string d'input est bien init / shutdown quand il faut.
- [ ] Gestion correcte de l'historique (lecture depuis un fichier, ecriture dans le fichier a la sortie)
- [ ] Changer history_add pour decouper les commandes multilignes, et centraliser l'appel a cette fonction
- [x] Ne pas utiliser argv[0] comme nom de programme, mais la macro NAME_42SH (chcrois)
- [x] Verifier la localisation des appels a error_set_context et error_print (J'ai un doute)
- [x] Mettre le lexer avec l'input et le parser pour ne pas avoir a le creer a chaque iteration dans la loop
- [ ] Changer la boucle de lecture en mode non interactif pour faire moins de copies
- [x] Rassembler les fonctions interactive et non_interactive.
- [x] ... Puis les separer a nouveau : en non-interactif, certaines erreurs entrainent la fermeture du shell.
- [x] En mode non-interactif le debug n'affiche que la premiere ligne
- [x] Un peu de refacto par ci par la.
- [ ] Changer quelques interfaces (notamment parametres dans le mauvais ordre)
- [x] **Segfault** sur les line continuation (shell_input l.19)
- [ ] ~Si ^D faire un saut de ligne. Si ^C pareil + afficher le prompt~ Pas à moi de le faire.
- [x] Verifier le retour de tous les appels a write ("vérifié")
- [x] 4 Nouveaux crashs !
- [x] Tout mettre dans une grosse fonction
- [x] Tout re-découper
- [x] **Segfault** avec `-d ast`
- [ ] La gestion de l'historique dans l'UI ne marche pas comme attendu pour un faible nombre de commandes

**Comment by Otaekek** [comment]
"Tester en lancant dans un programme qui pourrit les termcap (Dites moi que ca sert a rien si vous voulez, j'ai pas confiance)"
L'ui ne fonctionnera pas du tout, mais c'est pareil pour tous les shells.

**Comment by tmielcza** [comment]
Je veux verifier que le programme n'explose pas. Pas qu'il est utilisable.

**Comment by dkrmr** [comment]
Je ne vois pas pourquoi il exploserait. Le seul truc un peu chiant ce sont les paramètres de retour du `read`, respectivement `VMIN` et `VTIME`. Pour les autres settings ce n'est pas de notre ressort.

**Comment by tmielcza** [comment]
Moi non plus je ne vois pas. Mais je compte pas sur l'ignorance pour me sauver d'un crash potentiel.

**Comment by Otaekek** [comment]
![albert-einstein](https://cloud.githubusercontent.com/assets/8776538/23272774/d403d9c4-f9fc-11e6-9b69-11dd6993b0ee.jpg)

**Comment by tmielcza** [comment]
Merge avec #113, un CdC ici #124 et les trucs restants ici #125.
