### ISSUE TITLE
Le shell quitte en cas de signal fatal

### ISSUE THREAD

**Issue by dkrmr** [itheof/42sh-posix#127]
# Comment reproduire
* `42sh> sleep 100`
* Dans un autre shell: `$> kill sleep_pid`

La boucle principale quitte le 42sh si le module d'execution retourne une valeur différente de 0. Or en mode interactif il ne devrait pas.

**Comment by tmielcza** [comment]
Quand je le teste il n'y a pas de probleme.
On parle des signaux sur #152.
