### ISSUE TITLE
Crash du shell sur une input vide

### ISSUE THREAD

**Issue by dkrmr** [itheof/42sh-posix#129]
# Comment reproduire
Appuyer sur `Entrée` sur un prompt vide.

**Comment by dkrmr** [comment]
L'input renvoit une ligne qui ne contient qu'un `\n`
Le lexer lex et produit un tableau de 1 token de type `NEWLINE`
Le parser parse et dit que c'est une suite de token valide, la grammaire l'exige.
Sauf qu'aucun AST n'est crée car ce n'est pas possible. L'execution reçoit un AST qui vaut `NULL` et crash.
Un check devrait etre effectué, possiblement dans `lexer_clear_tokens`, pour empecher ce cas de ce produire.

**Comment by tmielcza** [comment]
Ce qu'on va faire pour le régler, et qui règlera par analogie d'autres problèmes, liés au Ctlr+C par exemple, c'est rajouter un état `DROP` (ou autre nom) dans la chaîne input/lexing/parsing, qui, que le shell soit ou non interactif, relancera la boucle pour attendre un nouvel input. Pas d'exécution, on ne met rien dans l'historique, etc.
En l'occurence, il sera renvoyé par la phase de lexing si a son issue le seul token de la liste est un \<newline>.

Ça semble cohérent ?

**Comment by Otaekek** [comment]
+1
