### ISSUE TITLE
Reflexion sur le module Historique

### ISSUE THREAD

**Issue by dkrmr** [itheof/42sh-posix#13]
Il semblerait que POSIX ne décrive pas précisément l'implémentation de l'historique dans le shell.
Une réflexion de groupe sur l'implémentation à suivre est donc nécessaire.

Voici une proposition de comportement:
* Au démarrage du shell en mode interactif, on charge l'historique via le fichier `$42SH_HISTORY`
* Le fichier d'historique ne contient que les _N_ dernières commandes.
* Chaque commande lancée par l'utilisateur est ajoutée à l'historique en mémoire. Mais rien n'est écrit sur le disque.
* Les commandes dépassant la limite de l'historique sont effacées (utilisation d'un buffer circulaire).
* À la sortie du shell, le fichier `$42SH_HISTORY` est vidé de son contenu et l'historique en mémoire, limité à _N_, est entièrement écrit dedans.

Bien évidemment la limite _N_, ainsi que le nom du fichier d'historique est a décidé.

## Changement de configuration de l'historique au runtime
Sur **sh** la variable d'environnement `HISTSIZE` donne la limite de l'historique.
Si au runtime on `source` un fichier comportant un changement dans la taille de l'historique, ce changement doit être reporté dans le shell courant.

**Comment by tmielcza** [comment]
La documentation de **sh** précise que le nom du fichier est déterminé par la variable d'environnement `HISTFILE`.

Après j'arrive pas à savoir ce qu'ils veulent dire quand ils parlent de l'édition de l'historique:
Est ce qu'on peut seulement chercher une commande pour la copier, l'éditer et la balancer au shell, ou est ce qu'on peut vraiment éditer l'historique ? Le comportement de **sh** quand on édite une commande de l'historique et qu'on fait entrée, il ne exécute la commande, la push dans l'historique sans modifier la commande éditée. Mais quand on édite, mais n'exécute pas de commande (par exemple en faisant entrée sur une ligne vide, et faut tester avec un Ctrl-C), les changements sont appliqués dans l'historique, donc dans le fichier !

Alors à mon avis, c'est un bug, parce que ça n'a aucun sens, mais faudrait en être sûr pour savoir si on reproduit ou pas le comportement.

**Comment by tmielcza** [comment]
Apparemment il existe un programme [history](http://ss64.com/bash/history.html) qui lui modifie bel et bien l'historique. Il est référencé (a priori) une seule fois dans la doc POSIX, dans la liste de utilities dont le comportement est `undefined`...

Sinon, si quelqu'un pouvait tester sur Linux comment se comporte **sh**, ce serait cool.

**Comment by tmielcza** [comment]
Sinon pour l'implémentation de la recherche dans ledit historique, voici quelques structures sympa:
[Trie](https://en.wikipedia.org/wiki/Trie)
[Suffix Array](https://en.wikipedia.org/wiki/Suffix_array)
[Suffix Tree](https://en.wikipedia.org/wiki/Suffix_tree)
[Generalized Suffix Tree](https://en.wikipedia.org/wiki/Generalized_suffix_tree)
[Ternary Search Tree](https://en.wikipedia.org/wiki/Ternary_search_tree)

**Comment by tmielcza** [comment]
D'ailleurs il avance ?

**Comment by tmielcza** [comment]
Est-ce que quelqu'un a trouvé la doc qui parle de `!` (l' "opérateur" qui fais des trucs avec l'historique en fonction de ce qui lui succède) ? @dkrmr @itheof (Je demande pas à ロドルフ, il lit pas la doc lololol)

**Comment by tmielcza** [comment]
Apparement c'est **bash**...

**Comment by dkrmr** [comment]
Étant donné que c'est optionnel dans le sujet et non POSIX, on passe sur l'expansion de l'historique pour le moment. On verra plus tard.

**Comment by itheof** [comment]
Implemente par 9d204dcf15b0521d7d936bf26fb037bd7aa8d925
