### ISSUE TITLE
Ne pas quitter le shell tant que l'input n'as pas renvoyé EOF

### ISSUE THREAD

**Issue by dkrmr** [itheof/42sh-posix#131]
La fonction `shell_loop2` ne devrait jamais return, meme en cas d'erreur. Le mode non-interactif du shell ne sert qu'au test automatisé. Et plusieurs fois le 42sh quitte alors qu'il ne devrais pas. Faussant ainsi les tests.

**Comment by tmielcza** [comment]
Tu parles de quelles erreurs ?

**Comment by dkrmr** [comment]
Exemple:
```sh
./42sh << EOF
> (;)
> echo a
> EOF
42sh: parser: unexpected token SEMI: ;
```

Il sort direct, sans executé le `echo`. Hors il devrait, pour les besoins des tests automatisés. `mksh` sort, car il est en mode non interactif. Mais nous on s'en fout, le "mode non-interactif" ne sert que pour les tests.

**Comment by tmielcza** [comment]
Les tests doivent être adaptés au shell et pas l'inverse.
Notre shell de référence c'est `mksh`, POSIX précise qu'en mode non-interactif on doit quitter en cas d'erreur de parsing, je vois pas ce qu'il nous faut de plus.
On modifie les tests et basta, le contraire serait ridicule.

**Comment by dkrmr** [comment]
Ok.
