### ISSUE TITLE
Comportement de mksh en cas de réception de signaux au moment de la lecture de l'input

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#138]
Quitte sans préavis: `HUP` `PIPE` `ILL` `TRAP` `ABRT` `FPE` `KILL` `BUS` `SEGV` `SYS` `XCPU` `XFSZ` `VTALRM` `PROF` `USR1` `USR2` et non POSIX:  `EMT`

Saute une ligne et réaffiche le prompt: `INT` `QUIT` `TERM`

Ne fait rien du tout: `ALRM` `URG` `TSTP` `CONT` `CHLD` `TTIN` `TTOU` et non POSIX: `IO` `WINCH` `INFO`

Autre: Bah `STOP`

**Comment by dkrmr** [comment]
Il faut rajouter un handler sur les signaux `INT / QUIT / TERM` dans le module d'input.
Ce handler devra set un flag en interne au module signal qui indiquera la reception du dit signal.
Le `read` s'arretera avec l'erreur `EINTR`.
A ce moment le module d'input devra checker le flag du module signal et si il est set, sortir avec une valeur précise pour indiquer qu'il a reçu un signal.

**Comment by dkrmr** [comment]
Tu peux mettre `KILL` dans autre. Il ne peut pas etre catché, donc le message que tu vois est affiché par le shell au-dessus.

**Comment by dkrmr** [comment]
Je viens de vérifier les signaux qui quittent `mksh` _avec un petit message_. Et c'est le shell au-dessus qui print le message, car l'un de ses enfants s'est terminé par un signal. Ce n'est pas `mksh` qui set un handler et print un message.

**Comment by dkrmr** [comment]
J'ai modifié le module signal pour correspondre aux nouveaux requirements.
Il n'est pas encore merge dans *master*, j'ai besoin de l'aide de @Otaekek  pour ajouter la logique ci-dessous dans le module d'input
```c
int read_input(void)
{
	while ((ret = read(fd, buf, size)) > 0)
	{
		...
	}
	if (ret == 0)
		return(EOF);
	else if (ret == -1 && errno == EINTR)
		return (SIGNAL_RECEIVED);
	else
		return (ERROR);
}
```

Tu trouveras les changements sur la branche `signal_input`. Dès que tu as fait les modifs @Otaekek, je teste que tout fonctionne bien et on merge dans *master*.

**Comment by dkrmr** [comment]
Je vais avoir besoin de toi @tmielcza pour placer les calls aux fonctions du module signal dans la shell loop.

**Comment by dkrmr** [comment]
Le fonctionnement des checks de signaux:
Si on est avant la phase d'input ou dans l'input, un handler est installé pour `INT/QUIT/TERM`, et le check se fait via `signal_should_we_drop_the_command`.
Si on est après la phase d'input, les signaux `INT/QUIT/TERM` sont bloqués, le handler est celu par défaut, et le check se fait via `signal_should_we_restart_the_loop`.

Pourquoi 2 méthodes différentes ? Parce que la secondes est bien meilleure, mais que pour l'input on ne peut pas faire autrement.

**Comment by tmielcza** [comment]
Pourquoi ne pas simplement bloquer les signaux pendant tout le process, et les débloquer au moment de l'input, après avoir mis les handlers ? Ça me semble plus simple et a peu près aussi efficace.

**Comment by dkrmr** [comment]
Parce qu'il faut pouvoir s'arrêter entre les phases si un signal est reçu et pas juste les débloquer quand on fork pour que le fils meurt immédiatement sans avoir vu le CPU.

**Comment by tmielcza** [comment]
Dans le man de fork:

> The child process is an exact duplicate of the parent process except for the following points:
> ...
> *  The child's set of pending signals is initially empty (sigpending(2)).

**Comment by tmielcza** [comment]
Dans tous les cas je trouve cette methode bancale.
Si on fait ca, c'est parce qu'en cas de parsing trop long, on peut annuler l'execution si on a recu entretemps un C-c.
Mais si la phase peut etre longue, ne vaut il pas mieux traiter le signal des qu'on l'a recu ? Comment fait on dans le cas d'un shell qui lit une commande gigantesque sur l'entree standard ? Impossible de l'arreter avant qu'il ait fini son parsing ?

**Comment by dkrmr** [comment]
My bad, je pensais qu'il les gardait. Donc le fork ne mourra pas immédiatement.
Par contre, je pense quand même qu'on devrait pouvoir s'arrêter entre les phases.

**Comment by dkrmr** [comment]
Tout les shells font la même chose. Tu ne peux pas checker la présence d'un signal toute les 10 instructions. Tu dois le faire à des endroits clé.
Cela dit je ne suis pas fermé à ta solution.

**Comment by tmielcza** [comment]
De tous les shells que j'ai testes (`sh, bash, dash, csh, zsh`), seul `mksh` (et nous) refuse de quitter apres un `C-c` pendant qu'il compute un enorme fichier.

**Comment by dkrmr** [comment]
Ça tombe bien, on se base sur `mksh` :D

**Comment by tmielcza** [comment]
On n'est pas obliges de reproduire les comportements foireux. J'appelle pas ca une fonctionnalite.

**Comment by tmielcza** [comment]
Remplacé par #152
