### ISSUE TITLE
Mettre a jour la gestion d erreur dans le module Variable

### ISSUE THREAD

**Issue by itheof** [itheof/42sh-posix#141]

**Comment by tmielcza** [comment]
Qu'est ce que ca signifie exactement, pourquoi on le fait, comment on le fait ?

**Comment by itheof** [comment]
L'idee serait d'avoir des messages d'erreurs generique qui seraient `error_set_context` dans le module, pour eviter des doublons dans les builtins: `42sh: {export,unset}: $VAR: read-only` par exemple

**Comment by tmielcza** [comment]
Que `get_var` et `set_var` affichent des messages d'erreur, donc ?

**Comment by itheof** [comment]
Reporté
