### ISSUE TITLE
Erreur de parsing

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#145]
Le parser ne comprend pas les redirections autour de subshells.
Exemple:
`<&0 (cat)`
Resultat:
`42sh: parser: unexpected token LPAREN: (`

**Comment by tmielcza** [comment]
Si j'ai bien suivi, c'est ce que dit la grammaire, ici:
```
command          : 
         (...)
                 | compound_command
                 | compound_command redirect_list
         (...)

compound_command :
         (...)
                 | subshell
         (...)
```
C'est à dire que les redirections, dans le cas des subshells, sont forcément **après** ceux-ci.

**Comment by dkrmr** [comment]
Oui, j'ai suivis la grammaire à la lettre.

**Comment by tmielcza** [comment]
Gnagnagna.
