### ISSUE TITLE
Reunion tutoriel

### ISSUE THREAD

**Issue by Otaekek** [itheof/42sh-posix#153]
Ce qui serait bien, c'est qu'on comprenne bien le fonctionnement des modules importants, d'une part parce que c'est bien, d'autre part pour la correction du (6 * 7 / 2)sh.

L'idee, ce serait que lors d'une reunion, chaque auteur d'un module explique en detail le fonctionnement de son module, son fonctionnement general, les pièges, les TRICKZZZ, les difficulté etc ...

En trouvant bien sur le moyen d'avoir un ordinateur a sa disposition.
Pour la liste des modules a review:

![screen shot 2017-03-15 at 6 11 50 pm](https://cloud.githubusercontent.com/assets/8776538/23961339/e94eafc6-09aa-11e7-9f4c-d8e6d6bbffbc.png)

Perso j'ai beaucoup de mal a comprendre le fonctionnement de l'AST.

Si possible, un peu de preparation fera pas de mal, pour fluidifier le tout car sa risque d'etre long.

**Comment by dkrmr** [comment]
Ce qui serait bien, c'est que vous compreniez bien que le projet ne sera pas terminé tant qu'il n'y aura pas assez de tests pour certifier qu'il est fini.

L'idée, ce serait que vous commenciez à vous bougez le cul à ce sujet. Que chaque auteur de module ne fasse pas que des tests uniquement pour son module, mais pour le fonctionnement général du projet. Et ainsi éviter les pièges, les TRICKZZZ, les difficultés que l'auteur d'un module aurait pu oublier, etc...

Perso j'ai beaucoup de mal à comprendre comment vous pouvez vous sentir encore légitime quand sur la liste des modules que tu présentes, à 2, vous n'en avez fait que 5 sur les 17 (Et encore je suis gentil).

Si possible, d'avoir eu à bosser un peu plus, aurait permis de fluidifier votre compréhension de la code base, et de ne pas vous y sentir totalement étranger.

A un moment, il faut arrêter de se taper dans le dos en mode *ouah tavu, suiv une spé c dur gro, mdr g pa lu. Vazy on branl r1 et ala f1 on dmd kil explik lol*.
Le projet ne se finira pas avec l'attitude du `gg ez no tests`.
Cessez de bidouiller des trucs (parce qu'en plus il faut qu'on passe derrière pour rattraper vos conneries) et commencez à construire du logiciel comme les développeurs que vous êtes censé être.

**Comment by Otaekek** [comment]
Dac, merci pour le "on branl r1"

**Comment by itheof** [comment]
Non constructif.
