### ISSUE TITLE
Reflexion sur l'implémentation du lexer-parser

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#16]
## Substitution unit with closed quotes
```bash
sh $> "$(ls")
>
```
Le shell redemande de l'input.
Dans l'exemple au dessus, il y a 3 niveaux d'imbrication: premier `"`, `$(`, deuxième `"`.
Pour que la commande soit complète, il faut fermer successivement tous ces niveaux d'imbrication: `")"`.
En fait, c'est nested.
Voici la bonne commande:
```bash
sh $> "$(ls"")"
```
ls est exécuté.

Pour gérer ça, une pile est recommandée.

Pour rappel, les quotes en elles mêmes ne sont pas nestables, alors que le sont les opérateurs de Parameter expansion, Command substitution et Arithmetic expansion.

**Comment by tmielcza** [comment]
En lisant la doc, il semblerait que seuls les `$(expr)` et `` `expr` `` ([_Command substitution_](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_03)) peuvent être _nested_ (Avec a priori possiblement des `$((expr))` et `${}` à l'intérieur cela dit...)

**Comment by itheof** [comment]
![screen shot 2016-10-05 at 9 15 36 am](https://cloud.githubusercontent.com/assets/8781784/19104352/51f66c88-8adc-11e6-9d38-c22829f2dfff.png)
Comportement de zsh

**Comment by tmielcza** [comment]
### Devinette
Que fais cette commande ?
`` `echo $(echo `echo ls`)` ``
¡ ǝxɐʇuʎs ǝp ɹnǝɹɹǝ ǝun ɐ ʎ lᴉ 'uǝᴉɹ :ǝsuodǝɹ

### Ah bon ?
En fait, la bonne façon de l'écrire est:
`` `echo $(echo \`echo ls\`)` ``
Echapper les backticks permet d'accéder à un deuxième (et dernier) niveau de `command substitution` par backtick. Pour accéder à des niveau supplémentaires, nous vous conseillons l'achat du ***Command Substitution Pack*** (~~-30% en ce moment!~~), qui comprend la syntaxe `$(command)` qui permet d'imbriquer en illimité vos `command substitution` !

Blague à part, et sans surprise, ça ne marche pas dans l'autre sens:
`` \`echo $(echo `echo ls`) \` `` reviendra à exécuter la commande `` `echo ``, qui n'existe pas (a priori).

### En Résumé:
les `` `command` `` ne peuvent pas être imbriquées ni entre elles ni via d'autres `$()` ou `${}` **sauf une fois** avec la syntaxe `` \`command\` `` à l'intérieur de la première. Dans les autres cas (du moins j'espère), `` \` `` correspond au caractère littéral `` ` ``

Et c'est chiant pour l'étape de token recognition. Voilà.

(Et pour répondre à la question du début puisque ce n'est toujours pas fait: la commande devrait exécuter `ls`)

**Comment by tmielcza** [comment]
Alors que la doc POSIX prétend le contraire, dans sh, la syntaxe `'text'` (des caractères entre simples quotes) **ne permet pas** de préserver littéralement tous les caractères contenus dans `text`.

En effet, `'\'` donnera `\`, mais `'\\'` donnera la même chose ! En gros, le backslash conserve ses propriétés *cheloues*, et il n'y a donc pas moyen d'écrire ce *fichu caractère* sans se préoccuper de son caractère échappatoire.

**Comment by itheof** [comment]
On suit POSIX. Rien ne nous impose d'imiter ce comportement de bash, qui doit faire ca pour des raisons de retro-compatibilite.

**Comment by tmielcza** [comment]
J'ai édité la partie sur les soucis de backticks. En fait il faudrait faire une page sur le Wiki pour résumer la phase de token recognition, étant donné que la doc POSIX pue des pieds.

**Comment by dkrmr** [comment]
@tmielcza Ok pour la migration vers le wiki
