### ISSUE TITLE
User interface terminé

### ISSUE THREAD

**Issue by Otaekek** [itheof/42sh-posix#17]
En theorie, j'ai finis d'implementer touts les features requises (on pourra ajouter des bonus facilement par la suite). Il ne manque plus qu'a tester et a mettre a la norme. Youpi.

**Comment by tmielcza** [comment]
Et repenser l'interface ! Quelques petites choses vont sans doute changer, notamment l'écriture du prompt.

**Comment by tmielcza** [comment]
Mais je sais pas utiliser Github....

**Comment by tmielcza** [comment]
Le comportement de sh quand on efface un caractère semble être de réécrire la ligne à la suite du curseur, puis effacer le reste de la ligne.
En outre, il semble utiliser les fonctionnalités d'insertion de caractères des termcap pour ... bah insérer des caractères.

**Comment by tmielcza** [comment]
Hahaha le mec il crash avec -fsanitize=address hahahahaha
HAHAHAHAHAHA
hahahaha... haha... ha... ha.. hhaaaa...
HahahahaHAHAHAHAHAhahaHAHAHAHAHAHAHAHAAHAHAHOHOHOHOHOHOHhohohoHOHOHOHOHOHOHOHOHHOHOHooooooooh HAHAHAHAHAHA
UN INDEX OVERFLOW HAHAHAHAHAHAHAHA MDRRRRRRRRRRRR LOL ROFL LFMAO
