### ISSUE TITLE
[UI] Refonte du diagramme d'algorithme

### ISSUE THREAD

**Issue by dkrmr** [itheof/42sh-posix#2]
* Éclaircir la gestion interne du buffer (_Edition environnement_).
* Ajouter une étape pour préciser l'output.
* Préciser le travail de l'étape `compute entry`.
* Changer `reset cursor` en `restore cursor position` ?
* Éclaircir le rôle de l'étape `data reset`

**Comment by tmielcza** [comment]
Le diagramme n'est plus représentatif de l'algo utilisé, donc en fait il faut le refaire complètement.

**Comment by dkrmr** [comment]
J'ai mis à jour le titre en conséquence.
