### ISSUE TITLE
Valeur de retour des tests unitaires

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#20]
Pour l'instant le binaire de test renvoie systématiquement 0.
Or, pour pouvoir tester via un script, il devrait retourner un code d'erreur en cas ... bah d'erreur.
Comme par exemple pour l'intégration avec Travis: les tests échouent mais ce n'est pas indiqué.

**Comment by itheof** [comment]
En fait il n'y a pas de tests pour le moment.

**Comment by tmielcza** [comment]
Mh, de mémoire c'était aussi le cas pour la lib42.
