### ISSUE TITLE
De l'utilité des itérateurs, nouvelle implementation ou suppression ?

### ISSUE THREAD

**Issue by Kerollmops** [itheof/42sh-posix#22]
@Otaekek(rcargou) demandant les itérateurs et moi meme (@kerollmops) les ayant supprimé lors de la reéfacto de la lib42, je propose une réflexion sur une implementation des itérateurs plus "intelligente".

Je suis même pour une suppression de ceux-ci, n'y voyant aucune utilité en `c`, en tout cas pas dans la lib42. Pourquoi ne pas implementer des structures iterator dans la lib42 ?

**Comment by Kerollmops** [comment]
Voici les raisons de la suppression (un peu rapide certe) des itérateurs:
- aucune utilité au niveau de la lib42
- en `c` on peu utiliser un incrémenteur
- le champ `size_t iterator` dans chacune des structures n'est pas approprié:
  - deux iterateurs sur la même structure devient impossible
  - ce n'est pas le rôle de la structure de gérer l'iteration

**Comment by Otaekek** [comment]
hitler.

**Comment by Otaekek** [comment]
#nazi hitler shoah.

**Comment by Otaekek** [comment]
Meme si je trouve aussi que c'est plus propre en terme de decoupage de ne pas intétgrer un itérateur basique a la structure, je trouve ca très pratique car cela permet d'éviter de créer une tonne de variables locals, ainsi que le nombre de paramètre des fonctions (lorsque tu veux faire persister l'iterateur entre plusieurs appel de fonction(et surtout lorsque tu as 3 ou 4 t_buffer)).
Donc je suis pour, si necessaire, implementer une classe itérateur, mais tout de meme conserver un iterateur basique dans les buffers.
ouai

**Comment by Kerollmops** [comment]
Heu l'iterateur peut très bien contenir le buffer sur lequel il iter non ?

**Comment by Otaekek** [comment]
Je devrais donc, pour avoir moins de variables, utiliser l'iterateur comme container de mon buffer ?

**Comment by Otaekek** [comment]
Parceque ca pour le coup je trouve pas ca tres propre !

**Comment by Kerollmops** [comment]
mais non c'est un paradigme fonctionnel (la consomption?: tu consume une data pour en donner une autre), Rust s'inspire de Scala, Haskell, Caml et autres languages fonctionnel.

ton iterateur ne serait pas un `t_iterator` mais un `t_string_iterator`.

**Comment by Otaekek** [comment]
C'est peut-etre propre avec un paradigme rust, mais en C, je trouve pas.

**Comment by Otaekek** [comment]
https://github.com/itheof/42sh-posix/blob/ui_history/src/user_interface/ui_loop/ui_loop.c
ZBLEH

**Comment by Kerollmops** [comment]
C'est ici ton utilisation des iterateurs ?
https://github.com/itheof/42sh-posix/blob/ui_history/src/user_interface/ui_loop/ui_loop.c#L65

**Comment by dkrmr** [comment]
> aucune utilité au niveau de la lib42
C'est un avis personnel ça, ce n'est pas un argument.

> en c on peut utiliser un incrémenteur
Et pas en rust ? Puisque qu'on peut aussi en rust, pourquoi ne pas le faire alors ?

Si on implémente une structure **Iterator**, ou `t_string_iterator`, qu'est ce qui se passe si on supprime un élément dans la liste ? Avant l'itérateur ? Après l'itérateur ? Ou l'élément sur lequel il pointe actuellement ?

**Comment by Kerollmops** [comment]
Regarde comment rcargou s'en sert dans le dernier lien, après on en reparle.

Et `t_string_iterator` inclus un pointeur sur la struct `t_string`, donc il sait si il pointe en dehors ou non et lorsque tu utilises ton iterateur et en meme temps que de faire des actions de suppressions/ajouts sur ta string, alors là c'est unsafe et c'est de ta faute !

**Comment by dkrmr** [comment]
Ok, je viens de voir comment @Otaekek s'en sert, principalement dans les fichiers handlers, et en faite je l'ai pas implémenté pour être utilisé comme ça XD

L'implémentation que j'ai faite des itérateurs gèrent les ajouts/insertions/suppression. Voilà pourquoi je trouve mon implémentation préférable à une structure à part.

**Comment by tmielcza** [comment]
Bof, tu peux toujours avoir des fonctions d'insertion ou deletion pour les itérateurs, qui appellent celles des `string` et se mettent à jour de manière *safe* (Sans doute).

De toutes façons comme visiblement personne s'en sert vraiment nulle part, la problématique **n'existe pas**. Si le but c'est juste de pas avoir à déclarer un compteur, bof.

Première utilisation que je trouve: [compute_user_entry](https://github.com/itheof/42sh-posix/blob/ui_history/src/user_interface/ui_loop/ui_loop.c#L55-L81)
A première vue, elle est utilisée comme un simple compteur, mais en regardant de plus près on la retrouve dans [find_and_execute_key](https://github.com/itheof/42sh-posix/blob/user_interface/src/user_interface/handlers/dispatch.c#L207) dans ce qu'on peut appeler un *effet de bord dégueulasse* (le sens de la boucle est obfusqué car le compteur est incrémenté à l'extérieur sans qu'on sache trop comment). Au final il ne sert pas d'itérateur mais de **pointeur** dans la string. Ce qui masque donc la manière dont il est utilisé.
Une autre utilisation est dans la fonction [diplay_entry](https://github.com/itheof/42sh-posix/blob/user_interface/src/user_interface/ui_loop/ui_output.c#L43-L70), où il sert également de curseur. Encore une fois, son utilisation est *bancale*.

Après concrètement les mêmes horreurs pourraient être faites avec n'importe quel type d'itérateur. S'il nous en faut impérativement pour des raisons **recevables**, on peut en discuter...

...Mais dans tous les cas je préfère qu'ils existent **à l'extérieur** de la `string` et si possible qu'ils couvrent un maximum de problématiques. Si on commence à rajouter plein de bordel dans nos structures pour gérer un cas ou deux, bah autant créer d'autres structures/fonctions plus spécifiques.
