### ISSUE TITLE
Tables de hash, gestion des commandes/alias/shell-functions

### ISSUE THREAD

**Issue by Kerollmops** [itheof/42sh-posix#24]
Refléchissons à l'implémentation de la table de hash qui permettra un accès rapide au path de la commande demandée par l'utilisateur.

Niveau petit algo de hash, il y a crc qui est dispo _(cmd-F **crc**)_ sur le site de [burtleburtle/crc](http://burtleburtle.net/bob/hash/doobs.html)

J'ai trouvé un article sympa qui parlait de [Robin Hood hashing](http://www.sebastiansylvan.com/post/robin-hood-hashing-should-be-your-default-hash-table-implementation/) et sur la [critique de la lib standard de Rust](https://ticki.github.io/blog/horrible/) aussi _(cmd-F **Robin Hood**)_.

EDIT

Un article sur le Robin Hashing avec des graphiques: http://codecapsule.com/2013/11/11/robin-hood-hashing/

**Comment by tmielcza** [comment]
> [...] au path de la commande demandée par l'utilisateur.

Comment ça ?

Pour moi ce sera surtout "utile" pour les noms de variables.

Concernant la fonction de hash, un truc dans [ce genre](http://stackoverflow.com/a/7666577) me semble suffisant.

Sinon le Robin Hood a l'air intéressant. Y'a plein d'autre techniques cela dit, et pour le coup l'[article Wikipedia](https://en.wikipedia.org/wiki/Hash_table#Robin_Hood_hashing) en répertorie un paquet. Pas sûr que ce soit utile de se prendre la tête cela dit, faisons au plus simple.

**Comment by Kerollmops** [comment]
mec c'est exactement ce lien que je cherchais (cse.yorku.ca/hash)[http://www.cse.yorku.ca/~oz/hash.html] !

**Comment by tmielcza** [comment]
D'accord, tu veux qu'on conserve les paths des commandes précédemment exécutées ... Ca me semble un peu overkill et ça va créer plein de problèmes. Par exemple il se passe quoi si le mec change le `PATH` ? Ou qu'il crée une fonction ou un alias ? On pète toute la table ? On vérifie que les valeurs sont toujours bonnes ?

**Comment by Kerollmops** [comment]
- Démarrage du shell:
 - le PATH est parcouru et chaque fichier exécutable dans chaque dossier est ajouté dans la table de hash (**nom du binaire** -> _chemin du binaire_) si la clef n'existe pas déjà, cela permet de gérer l'ordre des commandes: la première commande trouvée dans le PATH est exécutée

- L'utilisateur demande l'exécution de `rg`:
 - le shell regarde dans ses alias puis dans ses functions et enfin dans la table de hash
 - si il ne trouve rien, il parcoure le PATH à la recherche d'un binaire exécutable nommé `rg` et l'ajoute à la table
 - si il trouve un fichier mais ne peut pas l'exécuter, il fait de même et remplace la clef précédente dans la table

Si l'utilisateur met à jour son PATH, il doit source pour mettre à jour toute les commandes de la table interne. Si il ne source pas et que le shell ne trouve pas une commande dans la table de hash, le comportement est normal: le shell cherche le premier exécutable dans le PATH (qui vient d'être mis à jour). Ce n'est pas un comportement spécial.

**Comment by dkrmr** [comment]
L'étape que tu décrit au démarrage est trop lourde. Meme si zsh l'implémente, il semblerait, je trouve ça useless.
Si on tape une commande, on stocke son chemin dans la table de hash et c'est tout.
