### ISSUE TITLE
Test de retour NULL de malloc: idées

### ISSUE THREAD

**Issue by Kerollmops** [itheof/42sh-posix#25]
Je pense qu'il est possible de tester les retours NULL de malloc de manière propre.
On pourrait charger notre propre librarie dynamique malloc (contenant malloc, realloc, free...) et 'wrapper' les vrais fonctions du système (conflicts de noms ?), en les glissants dans ce genre de scope:
```c
#ifnedef
# define MALLOC_CRASH_AT 0 // each compilation increment this
#endif
static g_malloc_count = 0;

void    *malloc(size_t size)
{
    if (g_malloc_count == MALLOC_CRASH)
    {
        ++g_malloc_count;
        return (NULL);
    }
    ++g_malloc_count;
    return (malloc(size)); // this is the real malloc but name conflicts...
}
```

`MALLOC_CRASH_AT` est incrémenté à chaque compilation et à chaque fois le programme passe une série de tests

**Comment by itheof** [comment]
pas besoin de librairie dynamique. Autant faire un ft_malloc et faire un define ft_malloc(x) malloc(x) si DEBUG est unset

**Comment by Kerollmops** [comment]
Mouai...
Ça implique de devoir utiliser `FT_MALLOC` partout dans **notre** code mais il est possible que certaines fonctions du système continues d'utiliser le vrai malloc, là est l'intérêt de ma solution, tous les malloc seront gérés.

**Comment by dkrmr** [comment]
Ou vous utilisez `malloc_or_die`. Le retour est forcément un pointeur valide vers un espace mémoire.
Si `malloc` foire, la fonction quitte en affichant un message d'erreur.
C'est le meilleur moyen de gérer un `malloc` qui échoue.
