### ISSUE TITLE
De l'utilité des arbres binaires

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#3]
## Dans la recherche de commandes dans l'historique
Avec un arbre binaire la recherche peut se faire caractère par caractère, et on peut conserver la position pour monter ou descendre dans l'arbre à chaque fois qu'un caractère est ajouté ou retiré.
On pourrait le purger de temps en temps pour retirer les commandes trop anciennes et éviter qu'il prenne trop de place (paramétrable ?).

## Dans la recherche des built-ins
Sur un petit nombre d'entrées ce sera plus rapide qu'une table de hash et bien sûr beaucoup plus qu'une liste chaînée. Pas nécessaires mais toujours bon a prendre. En plus de ca comme on connait à l'avance le nombre de built-ins on peut transformer l'arbre en tableau, avec des offsets, fin je vous expliquerai. Ce sera chouette.

## Dans la gestion des collisions dans les tables de hachage
On peut mettre des arbres binaires en guise de buckets au cul des tables. Mais c'est sans doute un peu overkill.

## Dans l'exécution des commandes
Bah ouais l'AST quoi.

## O(log(n))
Y paraît.

## Conclusion
Azy on l'fait.

**Comment by dkrmr** [comment]
L'arbre binaire dans la table de hash est un peu overkill en effet. Un simple array, et on itère dessus suffit amplement AMHA.

**Comment by Kerollmops** [comment]
On avait pas parlé d'un buffer circulaire pour l'historique ? Ou la recherche c'est différent du stockage ?

**Comment by tmielcza** [comment]
Il y aurait 2 structures en fait: Une pour représenter l'historique sous forme de timeline (pour avancer, reculer...) et qui serait effectivement un buffer circulaire, et une qui le classe alphabétiquement (pour la recherche), et là un arbre me semble plus efficace.

**Comment by tmielcza** [comment]
En fin de compte, un arbre binaire ne couvrirait pas une recherche par sous-chaine dans l'historique, donc pas compatible avec Ctrl-R.
