### ISSUE TITLE
Using the malloc_or_die function

### ISSUE THREAD

**Issue by Kerollmops** [itheof/42sh-posix#39]
I propose using the [malloc_or_die](https://github.com/dkrmr/lib42/blob/master/src/memory/ft_memalloc.c#L33) function to avoid returning errors and managing messages for each malloc.
This makes the code clearer, cleaner and shorter !

**Comment by dkrmr** [comment]
C'est une très bonne idée !
Je l'ai justement codé pour ça. :)

**Comment by itheof** [comment]
Ca pourrait nous poser des problemes lors de l'execution de taches async. On pourrait se retrouver avec des process encore en vie alors que le shell a quitte.

**Comment by dkrmr** [comment]
Je ne pense pas. Si la fonction `malloc` foire, l'état du système est tellement incertain que même si on laisse des processus enfants le système les tuera pour récupérer de la mémoire.

**Comment by dkrmr** [comment]
Changement validé ? On peut fermer l'issue ?

**Comment by itheof** [comment]
Remplacer exit par l affichage d'un message d'erreur, puis on peut fermer l'issue !

**Comment by dkrmr** [comment]
Il faudrait le rajouter au wiki.

**Comment by dkrmr** [comment]
Actuellement je wrap mes fonctions dans `fatal_malloc`:
```c
fatal_malloc(string_init(...));
```

Mais le message d'erreur est généraliste, `malloc failed!`. Ce serait cool d'avoir la possibilité de rajouter un message d'erreur pour indiquer où dans le programme on vient de crash.

**Comment by Kerollmops** [comment]
un `assert` par example ? https://github.com/itheof/42sh-posix/issues/57

**Comment by dkrmr** [comment]
`assert` n'est pas utile que pour le debug ? La je parle au runtime en cas de `malloc` qui foire.

**Comment by tmielcza** [comment]
Si le malloc foire, est ce que c'est utile de savoir où ?
Eventuellement, on peut faire un assert pour le debug (plus d'infos), et juste un abort pour la release (plus pratique).

**Comment by dkrmr** [comment]
Il faut donc rajouter le call à `ft_abort` dans la fonction `fatal_malloc`
