### ISSUE TITLE
De l'utilité d'une norme

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#4]
Cela permet de garder un code un minimum clair et lisible pour tout le monde (Non, la norme 42 ne suffit pas, voire elle empire parfois les choses), plus débuggable et de compiler plus vite,

Voici quelques idées:

- Inclure dans les headers **tout** ce dont il a besoin pour être inclus, et **seulement** ce dont il a besoin.
_**Intérêt:** Accélération de la compilation (mininum de dépendances), lisibilité dans les headers._

- Déclarer `const` les données passées par pointeur en paramètre de fonction si elles ne sont pas destinées à être modifiées.
```c
// Quelle est la source ?
void *memcpy(char *s1, char *s2, size_t n);

// Plus explicite
void *memcpy(char *s1, const char *s2, size_t n);
```

- Les fonctions doivent recevoir d'abord les paramètres de **sortie**, puis les paramètres à **modifier**, puis les **entrées**.
```c
void func(char *output, char *update, int const *input1, int input2);
```
_L'ordre des paramètres est prévisible._

- Séparer les `typedef` des déclarations de types.
```c
// Wrong
typedef struct s_env
{
  ...
} t_env;

// Right
typedef struct s_env t_env;
struct s_env
{
  ...
};
```

- Les constantes sont précédées de `c_`.
   Les valeurs des `enum` sont en majuscule et précédées de `E_`.
_Comprendre facilement d'où viennent les symboles non déclarés dans le scope._

- Privilégier l'utilisation de variables constantes ou d'enum aux macros, quand ça a du sens.
_On peut voir les valeurs directement dans les `.c` (pour les constantes), les symboles apparaissent dans le binaire (debug), on peut référencer les variables par pointeurs, les valeurs sont typées._

- Utiliser les types du standard (`uint32_t`, `uint16_t`, `size_t`...) quand la taille doit être fixe (dans les `struct` et les `union` par exemple), et privilégier la lisibilité dans les variables ou paramètres de fonction (int, char...).

- Pas de pointeurs dans les `typedef`. Même pour les fonctions.
```c
// Wrong
typedef void (*foo)(int t);
foo func;

// Right
typedef void (foo)(int t);
foo *func;
```
_Éviter les confusions._

- Utilisation de constantes dans les structures quand ça a du sens.
_Éviter la modification de variables importante pour d'autres informations interne à cette structure._

- Les variables booléennes commencent par 'is' ou 'does'.
- Faire en sorte que la valeur booléenne `true` corresponde à une information positive.
```c
// Wrong (en plus c'est pas à la norme)
int does_fail, enabled, ok;
// Right (toujours pas)
int does_succeed, is_enabled, is_triggered;
```
- ~~Mettre des accolades pour les structures de contrôle, si y a la place (Ou faire en sorte qu'il y ait la place autrement).~~
**Edit:** En faisant ça la norme nous force à aérer le code, ce qui n'est pas désirable, et en faisant l'inverse (jamais de brackets si ce n'est pas nécessaire), le formatage des imbrications/suites de blocks de contrôle peut devenir inconsistant -> moins lisible. Donc pas de norme.

- Nommer les fonctions opposées de manière consistante: open/close, create/destroy, acquire/release, start/stop...

- Ne pas mettre le header 42 dans les sources.
_Prend de la place inutilement, Pollue les commits avec les changements de date et d'auteur des dernières modifications._

- Mettre les valeurs ambigües dans des macros, constantes ou énumérations aux noms plus explicites.
```c
// Wrong
fmt = tgetstr("vi", 0);
// Right
fmt = tgetst(TCAP_INVISIBLE_CURSOR, NULL);
```

- Écrire les entiers qui n'ont pas de valeur numérique (flag, addresse...) sous forme de littéraux hexadécimaux.
```c
#define STRUCT_OFFSET 0x10deadbeef
```

- Limiter les effets de bord, et les expliciter dans les noms de fonction quand il y en a.
```c
// Wrong
void  do_nothing(const char *not_modified) {
  modify((char *)not_modified);
  g_global += 2;
  read_things();
  print_things();
}
```

- Quelques mots-clés usuels et leur utilisation:
  - `len` : Une taille en nombre d'éléments.
  - `count` : Un compteur.
  - `size` : Une taille en octets.
  - `capacity` : Le nombre d'éléments que peut contenir un container.
  - `nth` : Pour parler d'un n-ième élément.
  - `find` : Trouver (plutôt que `search`, chercher).
  - `print` : Pour une fonction qui utilise `write` et écrit sur les sorties standard ou d'erreur.
  - `new` : Pour une fonction qui alloue de la mémoire pour créer et renvoyer une struct.
  - `init` : Pour une fonction qui prend une structure en paramètre et l'initialise.
  - D'autre trucs.

- Commenter, si nécessaire, dans les headers pour documenter les fonctions (si leurs noms ne le font pas déjà assez), et dans les sources pour documenter les détails d'implémentation.

**Comment by tmielcza** [comment]
Et il faut mettre tout ça dans le Wiki. Merci @dkrmr.

**Comment by dkrmr** [comment]
Pour le préfix sur les enums j'ai un avis différent.
Ce serait mieux de les garder en majuscules, pour bien voir que ce sont des constantes, et les préfixé par `E`

#### Exemples:
```c
enum e_key
{
    E_KEY_CTRL_A,
    E_KEY_CTRL_B,
    ...
}
```

**Comment by tmielcza** [comment]
Et pour les constantes ? On fait un truc spécial ou pas ?

**Comment by dkrmr** [comment]
Pour la section sur les accolades, éviter d'espacer du code. Un code compact est préférable AMHA

**Comment by tmielcza** [comment]
J'ai update la norme avec les trucs suivants:
- effets de bord.
- nomanclature (???)

**Comment by tmielcza** [comment]
J'ai rajouté une page dans le wiki (et d'autres trucs).
[OM NORME NORME](https://github.com/itheof/42sh-posix/wiki/Norme)

**Comment by Kerollmops** [comment]
Pourquoi mettre une explication de fonction au dessus du code et non au dessus des prototypes dans le header ? Ne serait-ce pas plus logique ?

**Comment by tmielcza** [comment]
Ce qui serait logique ce serait de commenter dans le header pour expliquer ce que le nom de la fonction ne fait pas (et ce n'est pas censé arriver mais admettons), et commenter le code dans les sources (pour documenter les détails d'implémentation, et là oui ça peut être chouettos, voire chouetounette).

**Comment by tmielcza** [comment]
En fait forcer les accolades, c'est nul (et l'inverse aussi).

**Comment by tmielcza** [comment]
Norme updated avec la clause suivante:
* La bonne manière d'écrire un type constant.

**Comment by tmielcza** [comment]
Updated:
* Noms des variables.

**Comment by tmielcza** [comment]
Updated:
* Catégories
* Quelques changements et fixes

**Comment by tmielcza** [comment]
Je réouvre, ce sera plus pratique pour en discuter.

Par exemple: j'ai galéré à trouver où était implémentée telle fonction, car aucun `.c` ne portait ce nom. Ce serait bien de documenter ça, par exemple, dans les headers, ou s'arranger pour que ce soit toujours clair.
