### ISSUE TITLE
Expliquez moi le fonctionnement des erreurs des builtins

### ISSUE THREAD

**Issue by Kerollmops** [itheof/42sh-posix#43]
```bash
$> unalias
unalias: usage: unalias [-a] name [name ...]

$> unalias notexisting
sh: unalias: notexisting: not found
```

Expliquez moi pourquoi le message d'`usage` commence par `unalias` et le message d'`erreur` commence par `sh` ? Y a t'il une règle ? Est-ce est une erreur de `sh` ?

**Comment by dkrmr** [comment]
[GNU Coding Standard: Formatting Error Messages](https://www.gnu.org/prep/standards/standards.html#Errors)
Il semblerait qu'il s'inspire un peu de cette doc.
Sinon voir du coté de POSIX si il y a des règles pour l'affichage d'erreur.
Si aucune règle POSIX n'existe concernant l'affichage des erreurs alors peut importe comment on la gère du moment que le message est clair sur l'erreur rencontrée.

**Comment by Kerollmops** [comment]
Mais ton lien c'est la gestion d'erreur pour les compilateurs...

Mais je vais aller chercher du coté de POSIX

**Comment by dkrmr** [comment]
On peut fermer l'issue ?
