### ISSUE TITLE
[CdC] Module Alias

### ISSUE THREAD

**Issue by Kerollmops** [itheof/42sh-posix#44]
L'interface: 
- [x] `int alias_init(void)`
Initiliaze the alias internal array, set the number of aliases to zero.

- [x] `void alias_shutdown(void)`
Desallocate all aliases and the internal array itself.

- [x] `void alias_clear(void)`
Only desallocate all aliases, the number of aliases become zero.

- [x] `const t_array *alias_get_all(void)`
Returns the internal array with all aliases as `char const *`.

- [x] `const char *alias_get_value(const char *name)`
Returns the value of an alias or NULL if it doesnt exists.

- [x] `int alias_set(char *name_value)`
Set an alias with a value and desallocate the old one if it already exists.

- [x] `int alias_unset(const char *name)`
Desallocate agiven alias.

Le module Alias doit pouvoir gérer:
- l'ajout d'un alias
- la suppression d'un alias ou de tous les alias
- la récupération d'un alias ou de tous les alias

La récupération d'un alias est la fonction la plus utilisée par rapport à l'ajout ou la suppression, j'ai donc décidé d'utiliser la dichotomie dans un tableau, qui permet une recherche en `O(log(n))` mais une insert/deletion un peu plus lente

**Comment by tmielcza** [comment]
Pourrais-tu expliciter le comportement des fonctions ?

Merci.

**Comment by Kerollmops** [comment]
Done ! 💚
