### ISSUE TITLE
User interface: Deduire la position du curseur par le calcul de la taille du prompt OU en ecrivant une requete au terminal.

### ISSUE THREAD

**Issue by Otaekek** [itheof/42sh-posix#45]
Actuellement, afin de déduire la position du curseur, nous écrivons une requête sur la sortie standard, puis nous bouclons jusqu'a ce que la réponse apparaisse sur l'entré standart. 
2 problème:
- Aucune garantie que la réponse n'arrive un jour (Boucle infinie ou système de timeout: BERK) .
- Apparition de trafic de donnée liée au système sur un FD reserve a l'utilisateur.

Une autre manière de faire serait de déduire la position du curseur en la calculant selon la taille du prompt. Il y a un risque d'override le prompt (Graphiquement) si jamais il contient des charactère UTF-8 ou si la commande précédente n'a pas print de \n.

Je serais pour la seconde méthode, car meme si elle est plus bug-friendly, elle provoque des bugs beaucoup moins violent. De plus, Bash possède les meme bug.

**Comment by Kerollmops** [comment]
Je suis complètement d'accord, avec toi, d'autant plus qu'il est possible d'ajouter un `%` si, avant l'affichage du prompt, tu demande la pos du curseur et qu'il ne se trouve pas à la column 0.
Pour les caractères utf8 c'est un truc qui pourrais se régler si on les gères un jour !

**Comment by dkrmr** [comment]
J'ai implémenté la méthode No2 sur mon 21sh. Elle est clairement plus compliqué que la première méthode.
Mais elle simplifie le code produit.

**Comment by dkrmr** [comment]
@Otaekek on peut fermer l'issue ?
