### ISSUE TITLE
ft_getline

### ISSUE THREAD

**Issue by itheof** [itheof/42sh-posix#47]
# Synopsis
```
#include "misc.h"

ssize_t    ft_getline(int fd, char **line);
```
# Description
The `ft_getline()` function reads a line from a valid file descriptor `fd`, delimited by the character `\n`, and stores the line along with its delimiter into `line`. The file descriptor must be set for blocking reads.
If `line` is `NULL`, the internal buffer for the specified `fd` is cleared even if input is remaining.
Caller can assume EOF whenever the terminating non zero char in line is not `newline`.
Caller is assumed to `free(3)` every `*line` on a succesful call.
 
Behavior is unspecified if a different fd is provided while some input is buffered.

# Return values
- \>0 Returns the length of the read line.
- 0 file cannot provide any more input or if `line` is `NULL`, the internal buffer for `fd` was successfullly cleared
- \<0 On error. If `errno` is set to `[EOVERFLOW]`, no delimiter was found in the first SSIZE_MAX characters. Otherwise, read(2) or malloc(3) errored and set `errno` accordingly.

**Comment by tmielcza** [comment]
Il faudrait remettre le buffer a une taille correcte (pas 1 quoi) et merge, pour pouvoir etre utilise dans la lecture des fichiers et strings en parametres.
Ca reste, a l'instar du lexer, un exercice de style etant donne l'absence d'implementation des structures de controle, special builtins, etc, qui rend la gestion des scripts quasi inutile, mais ca a le merite d'exister.

**Comment by tmielcza** [comment]
Ah, et la norme aussi.

**Comment by itheof** [comment]
On etait passe a un buffer de 1 car le main n'etait pas assez elabore. Il faudrait appeler getline uniquement lorsque l'origine de lecture est un fichier (et non un term par exemple).

**Comment by itheof** [comment]
Abandonné.
