### ISSUE TITLE
Sujets à discuter lors de la réunion du Vendredi 11/11

### ISSUE THREAD

**Issue by Kerollmops** [itheof/42sh-posix#50]
### Utilisation de global pour stdout et stderr

Les redirections seraient moins génantes à implémenter pour les builtins par example.
Par contre ça pourrait donner certains problèmes du genre utilisation du fd `1` au lieu de `stdout`.

### Utilisation d'un lexical analyseur

Ajouter dans le Makefile une règle qui permettrais de détecter les erreurs de logique ou de logique.

### Le systeme de gestion d'erreur
* Utilisation d'errno pour les fonctions systeme ?
* Implementation à suivre pour les erreurs de notre code base ?

### Passage au standard C11
* Avantage, inconvénient ?

**Comment by dkrmr** [comment]
Report de la réunion:
* Pas de globale
* Ajout de la règle du `checker` dans le makefile
* Utilisation d'`errno` validée
* C11 accepté.
