### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by dkrmr** [itheof/42sh-posix#54]
# Module de gestion des variables
## Interface
* macros: `VAR_FLAG_EXPORT` `VAR_FLAG_RDONLY`
* `extern char **g_environ;` Une entree est ajoutee automatiquement lorsque le flag `VAR_FLAG_EXPORT` est set sur une entree, et sa value n'est pas null.
* `void var_init(void);`
initialise l'environnement prive comme public. Avant son appel, g_environ n'est pas initialise et il est unsafe de le dereferencer.
* `void var_shutdown(void);`
detruit l'environnement prive comme public. Libere toute la memoire allouee.
* `int var_get(const char *name, const char **value);`
Si une entree `name` est trouvee, stocke sa valeur dans `*value` et retourne `NO_ERROR`. Sinon assigne `NULL` a `*value` et retourne `ERR_VAR_NOT_FOUND`
* `int var_unset(char const *name);`
Supprime l'entree au nom de `name`, ainsi que tous value/flags associes et renvoie `NO_ERROR`.Update `g_environ` si necessaire. Si `VAR_FLAG_RDONLY` est set pour cette entree, elle reste inchangee et `ERR_VAR_RDONLY` est renvoye. Sinon si aucune entree correspondant a `name` n'est trouvee, renvoie `ERR_VAR_NOT_FOUND` 
* `int var_set(const char *name, const char *value, int flags);`
Ajoute/modifie l'entree au nom de `name`. Si `VAR_FLAG_RDONLY` a ete set pour `name` et `value` n'est pas `NULL`, `var_set`  quitte immediatement et renvoie `ERR_VAR_RDONLY`. Sinon `value` est update si differente de `NULL`, et `flags` sont ajoutes a l'entree `name`. `var_set` maintient `g_environ` a jour si necessaire.

**Comment by dkrmr** [comment]
## Pourquoi proposer une implémentation qui prend en charge l'environnement alors qu'on à pas la réponse de Thor ?
Parce-que le sujet du 42sh simple qu'on validera ne sera pas **POSIX**. Donc aucune chance qu'on puisse utiliser les fonctions de la **libc**.
Si la réponse de Thor est positive, changer l'implémentation sera facile.
SI elle est négative, on aura déjà une implémentation qui fonctionne.

**Comment by Kerollmops** [comment]
Que se passe-t'il si l'on `export` un variable interne et que celle-ci est la `première` interne ?

**Comment by Kerollmops** [comment]
cf. `Comportement en cas d'execve`, donc `execve` duplique le tableau ?

**Comment by Kerollmops** [comment]
`int variable_set(const char *name_value)` pourquoi `const char *name_value` étant donné que le module est sensé pouvoir le `free` par exemple ?

**Comment by Kerollmops** [comment]
À la place de `int variable_set(const char *name_value)` j'aurais plutôt (le chien de mickey) vu `int variable_set_external(const char *name_value)` et `int variable_set_internal(const char *name_value)`.

Ou peut être `int variable_make_external(const char *name)` et `int variable_make_internal(const char *name)` et garder `int variable_set(const char *name_value)` qui la set en interne de base.

**Comment by Kerollmops** [comment]
```c
bool variable_is_export(const char *name);
```
deviendrait:
```c
bool variable_is_external(const char *name);
```

**Comment by dkrmr** [comment]
@Kerollmops 

> Que se passe-t'il si l'on export un variable interne et que celle-ci est la première interne ?

Tu passes de `[last_external] [NULL] [first_internal] [second_internal]` à
`[old_last_external] [old_first_internal] [NULL] [old_second_internal]`

> donc execve duplique le tableau ?

Oui.

> [...] étant donné que le module est sensé pouvoir le free par exemple ?

Le module duplique les strings envoyé, donc oui le paramètre est constant.

**Comment by dkrmr** [comment]
* Changement du prototype de `variable_is_export`
* Ajout des prototypes de `variable_make_XXX`

**Comment by dkrmr** [comment]
Actuellement la fonction `variable_is_external(...)` retourne un booléen qui indique si la variable est **externe**.
Hors quel comportement adopté si le nom n'existe pas ?
`false` n'est pas une réponse adéquate car il laisse à penser que la variable est **interne**.

La solution simple c'est le `define` avec un `int`
```c
#define VAR_IS_EXTERNAL 1
#define VAR_IS_INTERNAL 0
#define VAR_IS_NOT_FOUND -1
```
Ainsi que renommer la fonction en `variable_status(const char *name)`

Ce qui donnera comme code:
```c
if (variable_status("HOME") == VAR_IS_EXTERNAL)
```

Ou alors on peut switcher en macro:
```c
#define VAR_IS_EXTERNAL(n) (variable_status(n) == 1)
...
if (VAR_IS_EXTERNAL("HOME"))
```

Vos avis ?

**Comment by Kerollmops** [comment]
```c
enum e_var_scope {
 E_MISSING = 0,
 E_INTERNAL,
 E_EXTERNAL,
}
```

Cet enum permettrait un meilleur gestion de ce genre de cas:
```c
if (variable_scope("HOME")) {
 // do something if not missing
}
```

**Comment by dkrmr** [comment]
Changement ajouté @Kerollmops 

Je viens de finir l'implem avec les tests. Tout est push sur le remote.
Qui veut faire la review ?

**Comment by dkrmr** [comment]
PR: https://github.com/itheof/42sh-posix/pull/55

**Comment by itheof** [comment]
legacy:

## Implémentation
### Structure de données
Un unique tableau de pointeurs pour toutes les variables. Son organisation sera:
1. variables externes
2. valeur NULL
3. variables internes.

Un pointeur est constamment gardé sur le `NULL` séparateur.
Un tableau de flags (même format):
* **read-only**
* **allocated**

### Initialisation du module
Les variables contenues dans le `char **environ` sont des strings **read-only**.
Au lancement les pointeurs sont copiés dans la partie des variables externes, aucune duplication n'est effectuée.
Le flag **allocated** n'est pas set.

### Première modification d'une variable externe read-only (variable_set)
La nouvelle association `name=value` est alloué dynamiquement et l'ancien pointeur remplacé dans le tableau.
Le flag **allocated** est mis à jour.

### Ajout d'une nouvelle entrée dans la table interne (variable_set)
L'ajout est fait en fin de tableau, rien de particulier.

### Ajout d'une nouvelle entrée dans la table externe (variable_set + variable_make_external)
- La nouvelle entrée est placé à l'endroit du pointeur `NULL`
- La première entrée de la table interne est remplacé par le pointeur `NULL` de séparation
- Et celle-ci est ajouté en fin de table interne.

### Retrait de variable dans la table interne (variable_unset)
- La dernière entrée de la table interne remplace celle retiré.
- Réduction de la taille du tableau de 1.

### Retrait de variable dans la table externe (variable_unset)
- La dernière entrée de la table externe remplace celle retiré.
- L'emplacement de la dernière entrée de la table externe devient `NULL`
- La dernière entrée de la table interne prend la place de l'ancien `NULL`
- Réduction de la taille du tableau de 1.

### Exporter une variable de la table interne vers celle externe (variable_make_external)
- L'entrée de la table interne prend la place du `NULL`
- La première interne prend la place de la variable déplacée
- Le `NULL` prend la place de l'ancienne première interne

### Retrait de l'export d'une variable externe (variable_make_internal)
Une variable externe, qui est exporté dans l'environnement, à la possibilité de ne plus être exporté mais de rester dans la table interne.

- L'emplacement `NULL` est remplacé par la variable qui n'est plus exporté.
- La dernière entrée de la table externe devient `NULL`.
- L'ancienne dernière entrée prend la place de la variable qui n'est plus exporté.

### Gestion du tableau de flag
Celui-ci doit recevoir les mêmes opérations que le tableau des strings pour rester synchroniser.
Un code générique sera produit.

### Comportement en cas d'execve
On passe simplement le pointeur sur le début du tableau. Celui-ci comportant un `NULL` de séparation, il est considéré comme **Null terminated**.


## Interface

- [x] `int variable_init(const char * const *environ)`
- [x] `int variable_status(const char *name)`
- [x] `int variable_set(const char *name_value)`
- [x] `int variable_make_external(const char *name)`
- [x] `int variable_make_internal(const char *name)`
- [x] `int variable_unset(const char *name)`
- [x] `const char *variable_get_value(const char *name)`
- [x] `void variable_make_readonly(const char *name)`

**Comment by tmielcza** [comment]
> Obtention des flags par son nom.

Les flags de la variable je suppose ?

Sinon, ça marche comment maintenant ?

**Comment by tmielcza** [comment]
Ce serait bien d'expliquer pourquoi cette implementation repond a ce qui est demande par POSIX / le sujet du 42sh.

**Comment by itheof** [comment]
Pouvoir set des variables en garder la possibilite qu'elles valent null. pouvoir set des flags avant assignement/ pendant / apres (sans ecraser la valeur) plus facilement (plus pratique pour implem les builtins).

**Comment by itheof** [comment]
Une petite piqure de terminologie est necessaire. La PR devra s'y conformer avant d'etre merge.
- Ce qu'on appelle variable flag est un variable attribute.
- Une variable est unset lorsqu'aucune `value` ne lui a ete assignee.
- Une variable est null set lorsque sa `value` vaut la string "".
- Une variable est set et non null lorsque sa `value` est non null et != "".
Les termes precedents sont inferes  directement de la doc POSIX. Les suivants sont complementaires:
- Une variable est defined lorsqu'elle possede un ou plusieurs attributs.
