### ISSUE TITLE
[Discussion] String container

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#56]
### Disclaimer
**Il y a des choses a revoir, certains aspects on change, certaines explications sont en PLS.**

---

# Intro

De tous temps, la modification d'une ligne de commande (string) altère également les unités lexicales (tokens) qui lui sont associées.

Conclusion:
La création d'une structure adaptée à ce problème semble adapté.

# Problématique

La manière la plus simple d'avoir une vue dans une string, c'est d'utiliser des références absolues (pointeurs) ou relatives au debut de la string (indexes).
Si on modifie la string, les références se décalent et ne pointent plus nécessairement sur la même chose. Dans le cas de notre shell c'est un problème, puisque la string est découpée en unités lexicales dont le contenu va parfois être modifié (expansion).

# Solutions

* On peut simplement changer les pointeurs sur string des unités lexicales à chaque fois que des morceaux de la string sont modifiés. Mais ça implique concrètement de se balader avec tous les tokens (et plus généralement avec toutes les références sur cette string) dès qu'on veut la mettre à jour.
* On peut découper la string en morceaux. Modifier un token ne décalera plus les suivants, mais dans le cas de l'expansion, il faudra quand même faire des décalages d'offsets si on utilise des tokens pour représenter le debut/fin d'une expansion à l'intérieur d'un word.
* Si vous en avez d'autres...

# La structure [Name] (Trouver un nom)

Comme souvent, la meilleure solution est d'utiliser un niveau d'indirection supplementaire.
On reference le debut et la fin des mots (comprendre par la, une unite lexicale) avec des identifiants abstraits. Quand on veut lire ou modifier un mot, des fonctions se chargent de l'acces a la donnee du mot.
Une phrase ou un mot sont composes d'une liste de maillons qui representent des morceaux de chaine. Cette structure contient le debut et la fin, abstraits (identifiants) et physiques (pointeurs), du morceau. Quand la chaine est modifee ce sont ces maillons qui sont modifies.
Les identifiants sont generes simplement avec un incrementeur monotone.
Pour extraire un mot d'une phrase ou d'un autre mot, le maillon qui correspond au mot (s'il est unique) est scinde en deux, puis est ajoute un maillon representant le mot extrait entre les deux parties, de maniere a ce que l'identifiant de debut du premier maillon et celui de fin du dernier correspondent bien a ceux generes lors de la creation du mot duquel on extrait une partie. La nouvelle section se voit alouer deux nouveaux identifiants.

Supposons qu'on parte avec une chaine "abc" comme suit :
<pre>            [0 - 1]                                 'a b c'</pre>
Avec la liste de maillons representee par les couples d'identifiants, a droite par les caracteres correspondant.
L'extraction du mot "b" donnerait :
<pre>[0 - 2] -> [3 - 4] -> [5 - 1]                   'a ' -> 'b' -> ' c'</pre>
Pour referencer le deuxieme mot de la chaine, on utilisera les identifiants 3 et 4. Et les identifiants 0 et 1 representent toujours le debut et la fin de la chaine complete.
Supposons qu'on veuille remplacer "b" par autre chose:
<pre>[0 - 2] -> [3 - 4] -> [5 - 1]                   'a ' -> 'coucou' -> ' c'</pre>
Les identifiants restent les memes, mais les donnees relatives aux caracteres ont ete mis a jour pour pointer vers un "coucou". La chaine complete est "a coucou c" (Ce qui par ailleurs, ne veut strictement rien dire).

Bref, si vous avez compris et avez une meilleure explication a donner je suis preneur.

# Interface

```c
void <name>_init(t_<name> *);
void <name>_shutdown(t_<name> *);
t_id_pair <name>_push_word(t_<name> *, const char *new, size_t size_new);
void <name>_remove_word(t_<name> *, t_id_pair to_remove);
t_id_pair <name>_sub_word(t_<name> *, t_id_pair in, int start_offset, int end_offset);
void <name>_replace_word(t_<name> *, t_id_pair to_replace, const char *new, size_t size_new);
// (Je trouve pas de meilleur nom pour qu'on comprenne que ca cree une string sur la heap et y met la concatenation des morceaux situes dans la paire d'identifiants...)
char *<name>_get_sentence_str(const t_<name> *);
char *<name>_get_word_str(const t_<name> *, t_id_pair the_word);
```

Et basta.

**Comment by tmielcza** [comment]
Comme il est de bon gout de donner des noms consistants aux choses, je propose de parler de **word** ou mot quand il s'agit d'une unite lexicale qu'on recupere avec `_push_word()` ou `_remove_word()`, et qui est compose d'un identifieur de debut et d'un identifieur de fin, de **sentence** ou phrase quand il s'agit de la phrase complete composee de tous les mots (qui je le rappelle peuvent etre imbriques), et de **chunk** (bof, mais de toutes facons j'en parlerai pas) ou "ceaumor" pour parler des maillons internes a la structure, qui representent des mots ou des morceaux de mots, avec un debut et une fin. 

J'ai change un ou deux noms et rajoute deux fonctions : 
- `_push_word()`, parce que jusque la il n'y avait aucun moyen d'ajouter des mots sur un SuperStringLayer (il parait que maintenant c'est le nom officiel) vide. Comme son nom l'indique, il rajoute un mot a la fin.
- `_remove_word()`, qui devrait avoir le meme resultat qu'un `_replace_word()` qui passe une chaine vide, en plus verbeux/opti. Pour ceux qui n'ont pas compris: il supprime un mot.

Bien sur, si a tout moment on envoie un `t_id_pair` incorrect, que les offsets depassent la taille du mot ou autre, c'est teste par des `assert()` en mode debug.

J'hesite a remplacer les `t_id_pair` par un type plus opaque `t_word`. La question etant : est-ce qu'on est cense pouvoir travailler sur un mot qu'on n'a pas acquis directement avec `_push_word()` ou `_sub_word()`, et qu'on construit par exemple avec le debut d'un `t_id_pair` et la fin d'un autre ?
Je pense que non.

A priori cette structure contient tout ce qu'il nous faut:
* On cree les tokens au fur et a mesure en appelant `_push_word()`.
* On peut supprimer les blanks ou en general des morceaux de texte avec `_remove_word()`
* On peut travailler sur une partie d'un mot avec `_sub_word()`, pour enlever les quotes ou gerer l'expansion.
* On peut faire l'expansion avec `_replace_word()`.
* On peut recuperer le texte, pour l'execution par exemple, avec `_get_sentence()`.

Voila, je pense que ca couvre tous les besoin, si jamais j'ai oublie quelque chose faites moi signe.

**Comment by tmielcza** [comment]
Bon.
Il m'apparaît évident qu'il y a un problème de granularité avec cette implementation.
Et en plus de ça, c'est bordélique.

Le concept de "phrase", c'est a dire de grouper ensemble les mots dans un ordre précis, n'a aucun intérêt. Ça fait doublon avec la liste de tokens.
Si on ôte cette feature, on se rend compte qu'il ne reste que deux choses : 1) la gestion des mots et 2) l'allocation des morceaux qui composent les mots. En gros, un container de mots, c'est à dire deux structures en une.

On va simplifier ça avec une structure de mot qui permet toutes les actions qui nous intéressent, à savoir la possibilité de créer des sous-mots dans les mots et de l'édition qui conserve la structure des mots avec leurs sous-mots. Cette structure ne sera utilisée que par les tokens `WORD` et leurs dérivés, les autres n'en ayant pas besoin (car l'enum suffit pour connaître leur signification).

Ainsi voici les nouveaux prototypes :
```c
// (un)?initialization functions.
void word_init(t_word *, const char *word_str, size_t size_str);
void word_shutdown(t_word *);

// Returns the identifier to access the full word.
t_sub_word word_sub_main(const t_word *);

// Creates a sub-word and returns its identifier.
t_sub_word word_sub(t_word *, t_sub_word in, int start_offset, int end_offset);

// Replaces the sub-word data by the given string.
void word_replace_sub_word(t_word *, t_sub_word to_replace, const char *new, size_t size_new);

// Returns a string of the full word, allocated on the heap.
char *word_get_str(const t_word *);
```

Cette fois c'est la bonne ...

**Comment by tmielcza** [comment]
Tant qu'on y est, à quoi ça sert de récupérer la section du mot complet avec `word_sub_main()` ?
Ah oui, pour appeler `word_sub()` ensuite...
...Ce qui sera l'unique façon d'appeler`word_sub()`, donc :
```c
// Creates a sub-word and returns its identifier.
t_sub_word word_sub(t_word *, int start_offset, int end_offset);
```
semble plus approprié. Et plus de fonction `word_sub_main()`.

**Comment by tmielcza** [comment]
J'ai changé le titre, c'est pour l'instant tout sauf un CdC...

**Comment by Otaekek** [comment]
Je peine a comprendre pourquoi on utiliser des indirection dans une chaine de charactere pour referencer des mots, plutot qu'avoir directement une liste / array de structure contenant un toutes les information relative au mot.
Aled.

**Comment by tmielcza** [comment]
Quel genre d'informations ?
Et comme j'essaie péniblement de l'expliquer, si ce sont des informations relatives à un emplacement dans la string, pendant l'expansion ça décalerait tout.
Et à la fin il faut pouvoir récupérer la string *expended*.

**Comment by Otaekek** [comment]
Les informations serait des morceaux de string, nom pas des reference dans une grosse string, mais une string a part entiere. (plus eventuellement des meta-donnee). Du coup pas de probleme pendant lexpansion.
Pour recuperer la string extended, bah on merge.
Jai pas encore compris avec precision le role du lexer/parser, et par consequent de ton systeme non plus, du coup j'ai du mal a interpreter ton systeme avec precision.

**Comment by tmielcza** [comment]
C'est exactement ce que fait cette structure.
Les references peuvent etre n'importe ou.

**Comment by tmielcza** [comment]
De base elles sont dans la grosse string pour éviter de réalouer de la mémoire pour chaque mot.
Durant l'expansion, on remplace simplement les references.

**Comment by Otaekek** [comment]
Ok je comprend mieux.

**Comment by tmielcza** [comment]
Les cas qu'on doit pouvoir gérer grace à ce module (on va repartir de là):

*    Tilde Expansion
*    Parameter Expansion
*    Command Substitution
*    Arithmetic Expansion
*    Field Splitting
*    Pathname Expansion
*    Quote Removal

Si on peut délimiter les sub-words concernés par ces expansions à l'avance, on peut simplement effectuer toutes les passes d'expansion à la suite sans avoir à re-parcourir le word d'origine.
Dans le cas des Parameter Expansion, Command Substitution et Arithmetic Expansion, on veut pouvoir accéder au contenu à l'intérieur des parenthèses, ainsi qu'au bloc complet, parenthèses comprises (pour le remplacer).
Dans le cas du field splitting et du pathnme expansion, on veut potentiellement découper un word en plusieurs words.
Dans le cas tous les cas on veut pouvoir délimiter et supprimer / remplacer des sub-words dans un word.

**Comment by tmielcza** [comment]
Le système actuel permet d'avoir une base pour gérer tout ça mais il reste trois problème majeurs:
* La gestion de la mémoire
Le possesseur de la mémoire des string qui composent un word n'est pas le SSL. C'est l'appelant qui doit se charger de l'allocation et de la désallocation de ces strings. Ca crée de la complexité si elles doivent être gérées avec des malloc et des free individuels à l'extérieur: il faut pouvoir les stocker, éventuellement les free dynamiquement à la suite d'une expansion si elles ne sont plus utilisées, etc.
Pour éviter ce problème je propose d'allouer un gros buffer bien obèse dans lequel on push les strings au fur et à mesure, compactées, et qu'on free à la fin de l'exécution de la commande. Un seul pointeur à gérer. Simple et direct.
* Le design de la structure qui encapsule le SSL
Il doit appeler les expansions dans l'ordre, donc une simple liste de `t_sub_word` suffirait pour ça. Il y a aussi les inhibiteurs (quotes); pour ça il peut également conserver une liste. Mais quand si le word doit être découpé...
* La création des nouveaux tokens après le field splitting
... c'est plus embêtant. Si on décide de découper le SSL en plusieurs morceaux, il faudra aussi mettre à jour la structure du dessus en découpant la liste de `t_sub_word`, ce qui ne semble pas très pratique. Ou alors on fait les trois dernières étapes d'une traite, pour n'avoir au final qu'une liste de strings qui correspondent aux différents words générés par le field splitting et le pathname expansion, dépouillés de leurs inhibiteurs.

**Comment by tmielcza** [comment]
C'est de la merde, je close.
