### ISSUE TITLE
assert() & NDEBUG

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#57]
Cette macro est bien pratique quand il s'agit de pointer facilement des erreurs de code (acces en dehors des bornes d'un tableau, déréférencement d'un pointeur NULL, etc).
Aussi je propose qu'on pense à l'utiliser dans tous les modules bas-niveau qui ont une interface, et d'ajouter le flag -DNDEBUG à la compilation du projet quand le debug n'est pas activé.

On peut même mettre des messages avec ce petit trick:
```c
assert(("Out of bounds", n < 0 || n >= size));
```
Dans ce cas, il faut compiler avec `-Wno-unused-value` pour éviter le warning (puisque la string n'est pas utilisée).

**Comment by Kerollmops** [comment]
```c
assert(/* Out of bounds */ n < 0 || n >= size);
```

**Comment by tmielcza** [comment]
Faux.

**Comment by Kerollmops** [comment]
Je pourrais faire une petite "refacto" de la lib42 la semaine pro, car je n'ai que de la review de code à faire et 1/2 builtins à terminer

**Comment by dkrmr** [comment]
![Brace yourself](http://i.imgur.com/tS1w4nl.jpg)

**Comment by tmielcza** [comment]
Je rajoute le label `todo` : il faudrait rajouter le flag dans le Makefile.
Et puisque tout le monde semble `OK`, rajouter un ligne dans la norme, quelque chose du genre.

**Comment by dkrmr** [comment]
C'est ta proposition, on attend ta PR :D

**Comment by tmielcza** [comment]
Tkt, je me le garde pour plus tard.

**Comment by tmielcza** [comment]
La question c'est: Où est ce que je rajoute le flag ?
PROD ?

**Comment by tmielcza** [comment]
Rajouté via aa5dc4d5cf138bc3ce30211165ee3e9c4da87a6a.
Manque plus qu'ajouter ça à la norme.

**Comment by tmielcza** [comment]
Et c'est dans la norme.
Pensez à l'utiliser.

**Comment by dkrmr** [comment]
Le lien vers la section de la Norme pour les flemmards: https://github.com/itheof/42sh-posix/wiki/Norme#assert

**Comment by itheof** [comment]
hmmmm. J'aurais plutot mis le flag dans tous les cas sauf DEBUG=yes

**Comment by dkrmr** [comment]
Il n'y a que 2 cas il me semble, si `DEBUG` est actif, ou `PROD`
