### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by dkrmr** [itheof/42sh-posix#59]
## Interface
```c
struct  s_parser
{
    t_ast	ast;
    t_array *tokens;
    t_token *lookahead_token;
    size_t  index;
};

// Parser
int		parser_parse(t_parser *parser);
void	parser_print_error(t_parser *parser);

// AST
void	ast_debug_print(t_ast *ast);
```

### Type de parser
Le fonctionnement interne est **recursive descent**

### Comment fonctionne t'il ?
Une règle de la [grammaire POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10_02) correspond à une fonction.
Les fonctions sont appelées du haut vers le bas.
Les tokens correspondant à ceux attendus par la grammaire sont mangés par chaque fonction.
Si un token inattendu est présent, le **parser** sort et retourne une erreur.

### Fonction: parser_parse
Retourne une valeur dans l'enum d'erreur:
* `NO_ERROR`: Si tout va bien
* `ERR_PARSING`: En cas d'erreur.

### Fonction: parser_print_error
Affiche un message d'erreur avec le nom du token sur lequel le **parser** c'est arreté.
Elle n'est pas appelé automatiquement en cas d'erreur.

### Traitement des erreurs
En cas d'erreur le pointer `lookahead_token`, ainsi que le champ `index`, de la structure `t_parser` pointe sur le token problématique. Permettant l'affichage d'un message approprié.

### Comment est-il construit ?
La construction de l'AST est effectué par le **parser**.
Celui-ci est un arbre binaire et les feuilles seront forcéments des noeuds de type `simple_command`.

### À quoi il ressemble ?
Un diagramme se situe dans le dossier `doc/AST.xml` et celui-ci est visualisable sur [Draw.io](https://www.draw.io/)
Pour bien comprendre la forme de l'AST référé vous à la [grammaire POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10_02)

### Comment on s'en sert dans l'expansion et l'exécution ?
Les noeuds de types `simple_command` et `subshell` contiennent des structures qui listent les tokens atomiques.

Pour `simple_command`:
- `redirections`
- `words`
- `assignments`

Pour `subshell`:
- `redirections`

**Comment by tmielcza** [comment]
Ce serait bien d'avoir un peu plus d'explications, parce que vue d'ici la structure ne dit pas grande chose quand au fonctionnement interne.
Est ce que ca couvre bien toutes les problematiques de POSIX et du sujet du 42sh ?
Pourquoi la structure contient le tableau de tokens, alors qu'on peut selon moi le passer en parametre de la fonction `_parse()` ?
A quoi sert l' `index` ? Pour moi il est presque identique au `look_ahead_token`, dont je ne comprends d'ailleurs pas le sens. S'il est utilise uniquement pour la gestion d'erreur son nom devrait etre plus explicite.
En cas d'input incomplet, par exemple une parenthese ouvrante sans son homologue fermante, est ce que ces variables suffisent a conserver l'etat du parser pour qu'il soit reappele ulterieurement ?
D'ailleurs comment fonctionne ce parser en interne ?

**Comment by dkrmr** [comment]
> Est ce que ca couvre bien toutes les problematiques de POSIX et du sujet du 42sh ?

Qu'entend tu par **les problematiques** ?
Le parser s'affaire, pour le moment, à dire si la phrase a du sens selon la grammaire POSIX. Rien de plus.

> Pourquoi la structure contient le tableau de tokens, alors qu'on peut selon moi le passer en parametre de la fonction _parse() ?

C'est vrai que je pourrais juste recevoir le tableau de tokens, c'est la seule chose nécessaire. Par contre ça pose un soucis... En cas d'erreur, le champ `index` de la structure permettait de connaitre le token problématique, et ainsi afficher un message d'erreur adapté. Ce ne sera plus possible.

> En cas d'input incomplet, par exemple une parenthese ouvrante sans son homologue fermante, est ce que ces variables suffisent a conserver l'etat du parser pour qu'il soit reappele ulterieurement ?
Le parser est réentrant. Il ne garde pas d'état en mémoire. La structure gardera l'endroit ou le parser c'est arreté mais ça ne servira à rien. Le parser ne peut pas retourner dans un état profond directement.

> D'ailleurs comment fonctionne ce parser en interne ?

C'est un recursive descent parser. Chaque règle de la grammaire correspond à une fonction. Quand le parser rencontre un token, il choisit la règle qui correspond au token, l'appelle, et ensuite la fonction appelé effectue la meme chose. Tu descends ainsi dans les appels, jusqu'au brique basique des commandes (les redirections, words, etc...)

**Comment by tmielcza** [comment]
> Le parser est réentrant. Il ne garde pas d'état en mémoire. La structure gardera l'endroit ou le parser c'est arreté mais ça ne servira à rien. Le parser ne peut pas retourner dans un état profond directement.

Qu'est ce qui est réantrant ? La fonction `_parse()` ? J'espère bien.
Tu veux dire que quand il a besoin d'input supplémentaire, il doit reprendre le parsing depuis le début ? Ça ne serait pas le cas avec une machine à pile *sifflote* . En tout cas il faut expliciter le comportement : soit c'est pas géré, soit c'est géré et comment on le gère.

> En cas d'erreur, le champ index de la structure permettait de connaitre le token problématique, et ainsi afficher un message d'erreur adapté.
Ce ne sera plus possible.

Pourquoi ce ne serait plus possible ?

**Comment by dkrmr** [comment]
Dans quelle condition le parser peut avoir besoin d'input supplémentaire ?

**Comment by tmielcza** [comment]
`$> (`
`$> for var`
`$> for var in`

**Comment by dkrmr** [comment]
Étant donné qu'on se focus sur le sujet du 42sh pour le moment, seul le premier cas est à gérer.
