### ISSUE TITLE
Lexer

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#63]
# Problématique

Le rôle de base du lexer est de découper l'entrée utilisateur en léxèmes, qui seront ensuite donnés au parseur pour la création des commandes.
Tous les prérequis du sujet étant inclus dans les règles POSIX, le lexeur suit ces règles-là, notamment:

* Le **quoting**, qui permet d'ôter le sens des charactères spéciaux, en vertu des points [2.2.*](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_02) et  [2.3](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_03) (Et notamment la règle 4)
* La reconnaissance des **opérateurs** suivants :  **`<` `>` `>|` `<<` `>>` `<&` `>&` `<<-` `<>` `&` `&&` `(` `)` `;` `;;` `newline` `|` `||`** s'ils ne sont pas echappés, entre guillemets, dans un commentaire, ou faisant partie d'un mot, en vertue du point [2.3](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_03) (Et notamment les règles 2, 3 et 6)
* Les **commentaires**, en vertu du point [2.3](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_03) (Règle 9)
* Reconnaissance de certaines formes d'**expansion** (Arithmetic expantion, command substitution, parameter expansion) dans les mots, points [2.6](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06), [2.3](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_03) (Règle 5)
* Les **mots-clés** ne sont pour l'instant pas gérés (car absents du sujet 42sh)
* Les **io numbers** associés aux redirections, point [2.10.1](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10_01)
* Le shell doit lire suffisamment d'entrée pour pouvoir finir les guillemets et les expansions, point [2.3](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_03) (Règle 5)
* Un saut de ligne peut être échappé avec un antislash, les deux caractères sont alors retirés de l'entrée, point [2.2.1](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_02_01)
* Les mots sont séparés par des espaces ou des tabulations
* Il n'est indiqué nulle part que le lexeur est susceptible de renvoyer une erreur

# Implémentation

## Interface publique

* La règle de l'échappement du saut de ligne est gérée à part, avant l'analyse lexicale, avec la fonction
```c
int		remove_trailing_escaped_newline(t_string *input);
```
qui doit être appelée en boucle tant qu'elle renvoie `LINE_INCOMPLETE`. Les entrées doivent être concaténées avant d'être envoyées au lexeur.
* La structure `t_lexer` contient les informations sur l'état d'analyse à la fin du dernier appel à `lexer_lex()`.
* L'analyseur lexical est initialisé et détruit avec les fonctions suivantes :
```c
t_lexer		*lexer_init(t_lexer *lexer);
void		lexer_shutdown(t_lexer *lexer);
```
* L'analyse lexicale est effectuée avec la fonction :
```c
int		lexer_lex(t_lexer *lexer, t_array *tokens, const char *input);
```
Elle prend un `t_lexer` initialisé, un tableau de lexèmes initialisé à remplir et la ligne de commande à analyser.
Si elle renvoie `LEXER_INPUT_INCOMPLETE`, il faut rappeler la fonction avec la même structure `t_lexer`.
Elle est susceptible (bien qu'en pratique ça n'arrive jamais), de renvoyer `LEXER_ERROR` si une ligne de commande contient une suite de caractères invalides.
* Un léxème est représenté par la structure `t_token`, qui contient les informations sur son début dans l'entrée et son nombre de caractères. Son type est `enum e_token_type`, et sa valeur une de celles définies par cette enum.

## En interne

L'analyse lexicale se fait en trois phases : 
* Elle découpe l'entrée en léxèmes bruts (Opérateurs, mots, espaces)
* Elle catégorise plus précisément chaque mot, en fonction de sa place dans la ligne
* Elle retire les léxèmes inutiles à l'analyse syntaxique

### Automate à pile
L'automate utilise une table de transition tridimensionnelle.
Les dimensions correspondent à:
1. L'État
2. L'État de la Pile
3. Le Symbole

Pour comprendre les automates à pile: [Wikipedia](https://fr.wikipedia.org/wiki/Automate_%C3%A0_pile)

### Découpage
Le lexer utilise un automate à pile (`t_automaton`) pour effectuer cette tâche. 
La découpe d'un token s'effectue quand le symbole en cours ne peut pas être associé à l'unité lexicale en construction (token),
c'est à dire que la transision suivante résulterait en un état d'erreur.
Le type du token ainsi découpé correspond au dernier état de l'automate, juste avant l'état d'erreur.
Quand l'input se termine, l'unité lexicale en construction est découpée, sauf si la pile n'est pas vide.
Dans ce dernier cas, le lexer conserve l'état d'analyse à la sortie.
Ce qui permet de le rappeler plus tard, avec de l'input supplémentaire, pour compléter le token.

### Categorisation de tokens
Un retypage de certains tokens est effectué une fois la phase de découpage terminée.
Celui-ci permet d'apporter de l'information supplémentaire pour des cas ambigues:
* Les **mots-clés** (non supporté pour le moment car non 42sh sujet)
* Les **io numbers**
* Les **assignment words** (non supporté pour le moment)

### Retrait des lexèmes inutiles
Ce qui est retiré:
* Les espaces blancs
* Les commentaires

Ceux-ci sont inutiles et parasitent l'analyse syntaxique, car absent de la grammaire.

### Voulez-vous en savoir plus ?
Certaines précisions se trouvent dans la partie [*Rationale*](http://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xcu_chap02.html#tag_23_02_02_03).

**Comment by dkrmr** [comment]
Tu as déjà une issue ouverte pour le CdC du lexer : https://github.com/itheof/42sh-posix/issues/48
Un merge des deux ?

**Comment by tmielcza** [comment]
Il n'y en a plus.

**Comment by dkrmr** [comment]
@tmielcza On fait un squash/rebase local pour l'amener dans `master` ?

**Comment by itheof** [comment]
On peut close ?

**Comment by dkrmr** [comment]
C'est close.
