### ISSUE TITLE
alias/unalias

### ISSUE THREAD

**Issue by Kerollmops** [itheof/42sh-posix#64]
# Builtin Alias/Unalias
## Capacités
* Ajout d'alias/Mise à jour d'alias: `alias nom1=valeur1 nom2=valeur2`.
* Obtention d'alias par leurs noms: `alias nom1 nom2`.
* Obtention de tous les alias: `alias`.
* Retrait d'un alias par son nom: `unalias nom`.
* Retrait de tous les alias: `unalias -a`.

## Interface
Ce sont des builtins qui utilisent [le module alias](https://github.com/itheof/42sh-posix/issues/44).

**Comment by itheof** [comment]
D'apres http://pubs.opengroup.org/onlinepubs/9699919799/utilities/alias.html, l'affichage d'un alias doit etre quote de facon a pouvoir etre reecrit dans le shell et obtenir les memes alias.
C'est une feature commune avec pas mal de builtins, y compris `export`, `set`, `readonly` etc...
Il serait peut etre pas mal de faire une fonction utilitaire qui escape une string selon les regles de quoting du shell command langage

**Comment by itheof** [comment]
par contre j'ai remarque que sur `mksh` ils ne quotent pas l'alias-name. Ca ne me parait pas respecter la spec. A discuter

**Comment by itheof** [comment]
Et d'apres POSIX/BaseDefinitions : ```In the shell command language, a word consisting solely of underscores, digits, and alphabetics from the portable character set and any of the following characters: '!', '%', ',', '@'.

Implementations may allow other characters within alias names as an extension. ```

**Comment by tmielcza** [comment]
Suivons POSIX alors. De toutes façons on a depuis longtemps abandonné l'idée d'un shell POSIX de référence ...

**Comment by itheof** [comment]
Il faudrait aussi, a la maniere de bash, renvoyer une erreur lorsqu'une tentative est faite de set/unset avec un alias-name ne respectant pas la definition de la spec http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_10

**Comment by tmielcza** [comment]
Est-ce toujours d'actualite ?

**Comment by dkrmr** [comment]
Je pense qu'on ne le ship pas pour le moment. On verra quand le projet sera vraiment fini.

**Comment by tmielcza** [comment]
Ok.
