### ISSUE TITLE
history

### ISSUE THREAD

**Issue by Kerollmops** [itheof/42sh-posix#65]
# Builtin History
## Capacités
* Affichage de tout l'historique: `history`.
* Affichage des `n` dernières entrées: `history n`.
* Suppression de tout l'historique: `history -c`.

## Interface
C'est un builtin qui utilisent [le module history](https://github.com/itheof/42sh-posix/blob/master/inc/history.h).

**Comment by Otaekek** [comment]
Il y a que ca comme options ? Tu as pris quoi comme doc de reference ?
Pour bash c'est : https://www.gnu.org/software/bash/manual/html_node/Bash-History-Builtins.html

**Comment by dkrmr** [comment]
On en avait discuté, comme `history` n'est pas POSIX, on se contente de faire l'implémentation minimale, à savoir celle de `mksh`

**Comment by tmielcza** [comment]
La commande `history` ne prendra pas de parametres *n*.
Il reste quelques details a verifier avant de merge la PR.
Cette commande n'etant pas utilisable en mode non interactif, comment faire les tests d'integration sur criterion ?

**Comment by dkrmr** [comment]
Criterion c'est test unitaire.
Shellscript c'est test d'intégration.

**Comment by tmielcza** [comment]
TG.

**Comment by dkrmr** [comment]
La réponse est dans mon post précédent. On fait ça en shellscript. Et osef si `history` n'est pas censé fonctionner en non-interactif, on lui fait manger les commandes via `-c` ou lecture de **stdin** via pipe.

**Comment by tmielcza** [comment]
Donc, on implémente `fc` avec toutes les options ? Puisque c'est plus ou moins ce que fait `mksh`.
En shellscript, ça veut dire qu'on gère les alias ?

**Comment by dkrmr** [comment]
Non on n'implémente pas `fc`. On fait le built-in `history` minimum qui colle au comportement de `mksh`

**Comment by tmielcza** [comment]
Soit `fc -l [-nr] [first[last]]` ?
Dans ce cas le petit @Kerollmops etait a cote de la plaque.
Je me met dessus du coup.

**Comment by tmielcza** [comment]
Ce CdC est annule en faveur de #117
