### ISSUE TITLE
setenv/unsetenv

### ISSUE THREAD

**Issue by itheof** [itheof/42sh-posix#70]
`setenv name [value]`
`setenv name`
Set la variable `name` a la value `value`. Si `value` n'est pas precise, set `name` a null.  Marque la variable `name` pour export immediatement. 
Erreurs: 
- `too few arguments.`
- `too many arguments.`
- `read-only: <name>`
- `<name>: not a valid identifier.`

`unsetenv name1 [name2 ...]`
Unset les variables passees en parametre.
Erreurs:
- `too few arguments.`
- `read-only: <name>`
- `<name>: not a valid identifier.` -> dans le cas ou `name` ne se conforme pas a la definition donnee par POSIX d`un name

Ces builtins seront supprimes une fois le sujet de base rendu. Leur implementation est libre. Le retour en cas d'erreur peut etre n'importe quoi mais different de 0.

**Comment by dkrmr** [comment]
Pour des raisons de praticité, de conformance à POSIX, et de tests, on va calquer le comportement de `setenv` sur `export` et `unsetenv` sur `unset`.
Pour `unset` on ne considère que son penchant pour l'environnement vu qu'on ne gère pas totalement le support des variables.
Ca nous permet de nous référer uniquement à POSIX pour la spé des builtins.
Concernant les tests, comme on colle à `mksh` et qu'il ne connait pas `setenv/unsetenv`, on fait d'une pierre deux coups.
2 alias dans le builtins manager seront rajouté, pour `export` et `unset`.

Je pense avoir fini de les coder aujourd'hui, comme ça on aura un set de tests complet pour l'environ en fin de journée.

**Comment by dkrmr** [comment]
Rétropédalage, on va faire encore plus simple. Ils veulent des builtins pourris d'un shell pourris, on leur donne. Les fonctionnalités de `setenv/unsetenv` vont etre conforme à ce que le man demande, mais on ajoute 2 alias, `export` et `unset` pour pouvoir les tester dans mksh.
Facile et testable, on ne se prend pas la tete.

**Comment by itheof** [comment]
Les builtins sont merged. Pas d'alias export et unset car comportement different
