### ISSUE TITLE
Interface utilisateur

### ISSUE THREAD

**Issue by Otaekek** [itheof/42sh-posix#72]
## Résumé
L'objectif de ce module est d'offrir a l'utilisateur une méthode d'édition de ligne intuitive.
Cette premiére inplémentation sera conforme  a celles requises dans les sujets 21sh/42sh, en plus
de quelques bonus. Elle est incompléte vis-a-vis de la norme POSIX.

## Contrainte
- Fonctionner sur tous les terminaux qui sont possédent les TERMCAPS les plus triviales (Donc partout, sauf les terminaux DUMB)
- Être conforme aux sujets 21sh / 42sh (rappel: si l'édition de ligne n'est qu'un bonus dans 42sh, certains n'ont pas encore validé le 21sh)
- Être perméable a de nouvelles modifications afin d'étre conforme a la norme POSIX
- Ne jamais afficher des resultats incohérents.

## Charges
- Lire les données reçus sur l'entrée standard et les traiter.
- Afficher l'intégralité de la ligne de commande, si celle si a une taille inférieur a la taille de la fenétre.
- Afficher la ligne de commande sur plusieurs lignes.
- Disposer d'un curseur qui représente la position sur la ligne de commande dans laquelles les modifications seront insérées, représenté par un inversement des couleurs des charactére et du background a son emplacement.
- Pouvoir insérer des charactéres ASCII dans la ligne de commande.
- Pouvoir supprimé le charactére précédant le curseur de la ligne de commande.
- Pouvoir déplacer le curseur charactére par charactére, ligne par ligne, mot par mot ou se déplacer au debut ou a la fin de la ligne de commande.
- Pouvoir étendre la taille du curseur afin de selectionner plusieurs charactére dans la commande.
- Pouvoir couper ou copier les charactéres compris dans la selection, puis les coller.
- Pouvoir remplacer tous les charactéres compris dans la selection par un autre charactére.
- Pouvoir supprimer tous les charactéres compris dans la selection.
- Pouvoir valider la ligne de commande avec '\n'. 
- Pouvoir charger les lignes de commande enregistrées dans l'historique.
- Avoir une méthode basique d'auto-complétion.
- Pouvoir signaler la volonté de l'utilisateur de quitter le shell, lorsque CTRL+d est préssé.

## Charges temporaire
- Afficher un prompt. Il est acceptable de laisser cette tache a l'UI pour la correction du 42SH, mais pas pour la validation POSIX

## Interface
````
 t_string ui_get_user_input(void)
````
Traite tous les données reçu sur l'entrée standard, jusqu'a ce que la ligne soit sois validé, sois quitté, puis retourne le resultat.
Le pointeur sur char de la structure t_string sera NULL si ctrl+d a été préssé.
Le \n de validation de commande sera compris dans la chaine de charactére retournée.

## Limite
- Impossible d'insérer des tabulations (a peu prés 2 jours de travails pour palier au probléme).
- L'ui devient de plus en plus lente, au fur et a mesure que la taille de la ligne de commande augmente (3 jours de travail).
- Provoque des resultat incohérents, si jamais la position du curseur en absisse n'est pas égal a 0 au moment ou l'ui est appelé.
- Ne fonctionne pas sur les terminaux DUMD (1 jour de travail).
- Ne répond pas a toutes les spécifications de la norme POSIX (1 a 2 semaines de travail).

## Notes
Certaines features ne sont pas encore en place dans la PR en cours.

**Comment by tmielcza** [comment]
Pourquoi avoir changé le titre ? Quand est ce qu'on a changé la convention pour nommer les issues ?
En plus UI = User Interface = Interface Utilisateur, c'est un poil redondant, non ?

**Comment by dkrmr** [comment]
Merge: 0f86ddb
