### ISSUE TITLE
is_name/is_alias_name

### ISSUE THREAD

**Issue by itheof** [itheof/42sh-posix#73]
`bool    is_name(const char *string, size_t len);`
Verifie que `string` matche la definition POSIX de [Name](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_235)
`bool    is_alias_name(const char *string, size_t len);`
Verifie que `string` matche la definition POSIX de [Alias Name](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_10)

**Comment by tmielcza** [comment]
Pourquoi passer la taille en paramètre et utiliser une *magic value* ?
Si c'est pour pas faire de copie, il faudra en faire de toutes façons pour l'exécution (il me semble).
Et dans quel cas la magic value est utile ? A la suite d'une expansion, sans doute, mais ça veut dire qu'on garde un flag pour savoir si le WORD a été expand, juste pour savoir comment faire cet appel ?

**Comment by tmielcza** [comment]
En outre je préfère appeler ces fonctions `is_valid_name` et `is_valid_alias_name`. Plus clair et précis.

**Comment by tmielcza** [comment]
Il faudrait aussi une fonction pour checker ceci: [Parameters and Variables](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_05)
En pratique il s'agit d'extraire le plus long nom possible à la suite d'un `$`, ou rien si par exemple `echo "$"`. Dans ce cas, est ce qu'on considère un nom de variable invalide ou juste qu'il s'agit du caractère `$` ?

Sinon, rien dans POSIX ne dit qu'un nom vide est impossible. Et quand on regarde les erreurs des shells de référence, ils ne le considèrent pas comme une erreur :
La commande est `""`.
Zsh:
`zsh: permission denied:`
Mksh:
`mksh: : can't execute: Is a directory`
Et ce qui est, selon moi, l'erreur la plus logique, Bash:
`bash: : command not found`

Si on considère que `"$"` est une erreur, ça peut être considéré comme une erreur de lexing.

**Comment by itheof** [comment]
Go faire un cahier des charges pour l expansion ou noter ca ailleurs
