### ISSUE TITLE
Doc Makefile

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#76]
Il serait judicieux de documenter un peu l'utilisation du Makefile.

Voilà.

**Comment by dkrmr** [comment]
Qu'est ce qui te pose problème ?

**Comment by tmielcza** [comment]
L'utilisation de PROD, SAN, etc, ainsi que de certaines regles.

**Comment by tmielcza** [comment]
On va dire que c'est expliqué dans le README.
