### ISSUE TITLE
Annulation temporaire du module d'expansion + liste des features optionnelles sur lesquelles nous allons travailler.

### ISSUE THREAD

**Issue by Otaekek** [itheof/42sh-posix#77]
Apres avoir revisité le sujet du 42sh, j'ai constaté que nous possedions ou pourions facilement posseder 6 features optionelles sur 5. Etant donnee que l'objectif est de valider le sujet le plus vite possible, je propose que l'on ne se focus que sur celle-ci. Le module d'expansion et par consequent temporairement annulé.

## Liste des features optionnelles que nous allons faire:
- Les inhibiteurs """ (double quote), "’" (simple quote) et "\\" (backslash).
- Les redirections avancées : l’aggrégation des sorties de fichier et le heredoc "<<".
- L’historique des commandes et les builtins history et "!" avec toutes leurs options
si elles en ont.
- Edition de ligne telle que demandée dans le ft_sh3.
- Complétion dynamique

et eventuellement: 
-  Les sous shells avec les operateurs "()".

**Comment by dkrmr** [comment]
Can't vote enough !

**Comment by tmielcza** [comment]
Les inhibiteurs font partie de l'expansion, en theorie.
Qu'est ce qu'ils entendent par "completion dynamique" ? C'est vague. Ca peut etre relou.
Si on fait les sous-shells autant faire les backticks.
Et il me semble qu'on a deja de bonnes bases pour les variables, `unset` et `export` ?
Le globbing c'est mort.
"Les descripteurs de fichiers et la builtin `read` avec toutes ses options", c'est complique a faire ? Ca m'a pas l'air.

**Comment by dkrmr** [comment]
Les inhibiteurs en font partie pour la phase de **quote removal** mais celle-ci est plutot simple comparé aux autres.
La partie sur les variables est useless sans la possibilité d'inséré des variables dans la commande, et donc de faire du **paramter expansion**.

**Comment by tmielcza** [comment]
Ne peut on pas le faire ? Si on ne gere pas le field splitting ni les imbrications d'expansion, ca ne me semble pas sorcier.

**Comment by Otaekek** [comment]
Pour la completion dynamique on a le champs libre, donc c'est plutot facile.
Ah bon ? sous-shell == backtic ? Si cest vrai autant le faire effectivement.

**Comment by dkrmr** [comment]
Avant de vouloir finalement partir sur toutes les features parce que "Yolo ça à l'air simple", essayons déjà d'avoir une exécution potable.

**Comment by tmielcza** [comment]
ftg

**Comment by tmielcza** [comment]
On est tous d'accord, je ferme. C'est en cours ou fini : 
#109 #103 pour le quoting
#93 pour le heredoc
#117 (en cours de merge) #106 pour l'history
l'UI est merge depuis longtemps
#118 pour la completion (en cours, il faut merge et cabler avec l'UI)
les subshells sont geres dans le lexing, le parsing, et bientot dans l'execution (wip)
D'autres trucs en cours egalement. C'est le bordel.
