### ISSUE TITLE
Macro de Debug

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#81]
Je ne sais pas trop ce que vous voulez pour débug, mais j'espère que ces quelques modestes macros vous satisferons:
```c
#ifdef NDEBUG                                                                                            
# define DEBUG(X)                                                                                        
# define PRINT_DEBUG(STR, ...)                                                                           
# define PRINT_DEBUG_INFO(STR, ...)                                                                      
#else                                                                                                    
# include <stdio.h>                                                                                      
# define DEBUG(X) (X)                                                                                    
# define PRINT_DEBUG(STR, ARGS...) fprintf(stderr, STR "\n", ##ARGS)                                            
# define PRINT_DEBUG_INFO(STR, ARGS...) fprintf(stderr, "debug@%s:%d: " STR "\n", __FILE__, __LINE__, ##ARGS)    
#endif
```

Explications :
Il y a deux blocs principaux, un où sont definie des macros vides (quand le debug est desactivé) et un où sont définies les véritables macros.
Le deuxième bloc inclus `stdio.h` puisqu'il s'agit d'afficher du debug.
Les macros utilisent `fprintf()` histoire d'écrire sur la sortie d'erreur.
La première exécute simplement du code, la deuxième écrit une string formatée sur la sortie d'erreur ainsi que la troisième, qui rajoute des infos sur le fichier et la ligne où le débug est appelé.
Elles sont variadiques pour pouvoir être utilisées comme les fonctions `printf()`: `ARGS` représente un ou plusieurs paramètres. La syntaxe `##ARGS` est utilisée pour enlever la virgule précédente si jamais la liste d'arguments est vide.
J'ai rajouté des sauts de lignes à la fin des strings de debug, ça me semble plus pratique à utiliser comme ça mais on peut les enlever tkt. Pareil pour le formattage de `PRINT_DEBUG_INFO` (qui d'ailleurs n'est peut être pas utile mais c'est toujours sympa de pouvoir mettre du débug un peu partout et savoir où c'est appelé, enfin c'est le cas quand on ne sait pas se servir de lldb).

Cela s'utilise comme ceci :
```c
DEBUG(fprintf(stderr, "Debug\n"));
PRINT_DEBUG("Debug (super utile me direz %s)", "vous");
PRINT_DEBUG_INFO("Pareil");
```
Et cela affiche :
```
Debug
Debug (super utile me direz vous)
debug@test.c:17: Pareil
```

**Comment by dkrmr** [comment]
Je n'avais pas vraiment ça en tete quand je parlais de retirer automatiquement les fonctions de debug de la compilation pour le rendu final.

**Comment by tmielcza** [comment]
Tu les mets dans un `DEBUG()`.
