### ISSUE TITLE
[CdC]: Bonus obligatoire: Historique

### ISSUE THREAD

**Issue by Otaekek** [itheof/42sh-posix#82]
# Introduction
Ce cahier des charges décrits la listes des charges a implementer pour completer le bonus obligatoire du 42sh: le module historique.
"L’historique des commandes et les builtins history et "!" avec toutes leurs options
si elles en ont."

## Charges
- Ajouts des entrees utilisateurs dans le module historique, après la fin de la phase de lexing.
- Pouvoir se ballader dans l'historique depuis l'UI.
- Implementation des builtins history et "!" avec leurs options.

**Comment by tmielcza** [comment]
Ca doit bien etre la 10eme issue qui concerne l'historique.
Il est en cours de merge ici : #120 et l'issue est #117
