### ISSUE TITLE
Recherche de la commande

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#83]
Voici ce que POSIX nous dit à ce sujet : [Command Search and Execution](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_01_01)

Et un diagramme qui résume tout ça : 
![](https://rawgit.com/itheof/42sh-posix/module_exec/doc/Command_Search_and_Execution.svg)

Une seule fonction:

```c
int     find_command(t_command *cmd, char const *name, char const *env_path);
```

Elle détermine si *name* est un builtin ou un programme, présent dans un des répertoires de *path* (formaté comme dans l'env) ou fourni sous forme de chemin complet.

Le `t_command` est une union qui peut être soit un pointeur sur fonction de builtin, soit un chemin complet vers un programme.

```c
union   u_command
{
    const char *path;
    t_builtin *builtin;
};
```

La fonction renvoie l'une de ces valeurs:

```c
#define FOUND_BUILTIN
#define FOUND_PROGRAM
#define ERROR
```

Respectivement si ont été trouvés un builtin, un programme, ou s'il y a une erreur.
Dans ce dernier cas, utiliser le module d'erreur pour récupérer le code et afficher un message.

TBD:
- Pour le POSIX, la commande peut aussi être une fonction, un special builtin ou un script.

**Comment by tmielcza** [comment]
J'ai édité le CDC, l'ancienne version étant selon moi un peu bancale. Là on a quelque chose de clair et pratique, avec une seule fonction qui fait le travail.
Dites moi ce que vous en pensez.
S'il vous plait.

**Comment by dkrmr** [comment]
Il y a deja un `typedef` qui s'appelle `t_command` (dans l'AST).
Sinon c'est parfait !

**Comment by tmielcza** [comment]
Edit: `find_command` prend désormais également une string pour le path.

**Comment by tmielcza** [comment]
À la lumière d'une lecture approfondie des man de `access`, `stat` et `execve` ainsi qu'à une intense réflexion, l'approche suggérée par ce CdC s'avère perfectible (dans le sens où c'est de la merde).

D'abord, il y a un problème d'accès concurrent aux fichiers : entre le moment où on détermine que le fichier est exécutable et son exécution effective, l'état du fichier peut changer.

Ensuite il y a la gestion d'erreur, qui doit du coup se faire à deux endroits différents au lieu d'un.

En résumé, dans notre cas le meilleur moyen de savoir si un fichier est exécutable, c'est de tenter de l'exécuter et voir ce qui se passe. Je propose donc de supprimer ce CdC pour le combiner à celui qui concernera l'exécution.

**Comment by dkrmr** [comment]
Ça me va comme approche. En faite tu peux juste retirer les checks pour les droits d'exécution mais garder ce CdC.

**Comment by tmielcza** [comment]
Les plans ont change : pour l'execution, les fonction ne se contentent pas de faire une recherche mais executent directement les commandes.
Une implementation similaire a ete faite pour l'autocompletion (en cours).
Est ce que quelqu'un d'autre a besoin de trouver une commande / builtin par son nom ?

**Comment by tmielcza** [comment]
Qu'est ce que ça fait encore là ça ?
