### ISSUE TITLE
Parser/AST

### ISSUE THREAD

**Issue by dkrmr** [itheof/42sh-posix#84]
# Parser/AST

## Interface

```c
struct  s_parser
{
    t_ast	ast;
    t_array *tokens;
    t_token *current_token;
    size_t  index;
};

void	parser_init(t_parser *parser, t_array *tokens);
int		parser_parse(t_parser *parser);
void	parser_print_error(t_parser *parser);
void	parser_shutdown(t_parser *parser);
```

----
### Comment fonctionne le parser ?
Il implémente la grammaire demandée par le sujet ([BNF 42sh](https://github.com/itheof/42sh-posix/blob/430f2f6c9848f49faf1ef7031ffb0d3bbd9700d1/doc/grammar.bnf)) , tout en restant en accord avec celle de POSIX ([POSIX Shell Grammar](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10_02))
Une règle de la grammaire correspond à une fonction.
Les fonctions sont appelées du haut vers le bas.
Les tokens correspondant à ceux attendus par la grammaire sont mangés par chaque fonction.
Si un token inattendu est présent, le **parser** sort et retourne une erreur.

### Que se passe t'il en cas d'erreur ?
Le **parser** retourne une valeur dans l'enum d'erreur:
* `NO_ERROR`: Si tout va bien
* `ERR_PARSING`: En cas d'erreur.

### Comment afficher un message d'erreur en cas d'erreur ?
La fonction `parser_print_error` affiche un message d'erreur avec le nom du token sur lequel le **parser** s'est arrêté.
Elle n'est pas appelée automatiquement en cas d'erreur.
En cas d'erreur le pointer `current_token`, ainsi que le champ `index`, de la structure `t_parser` pointe sur le token problématique. Permettant l'affichage d'un message plus approprié si besoin.

### Comment l'AST est-il construit ?
La construction de l'AST est effectuée par le **parser**.
Celui-ci est un arbre binaire et les feuilles seront forcément des noeuds de type `simple_command`.

### À quoi il ressemble ?
Un diagramme se situe dans le dossier `doc/AST.xml` et celui-ci est visualisable sur [Draw.io](https://www.draw.io/)
Pour bien comprendre la forme de l'AST référez vous à la [grammaire POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10_02)

### Comment on s'en sert dans l'expansion et l'exécution ?
Les noeuds de types `simple_command` et `subshell` comportent des structures qui référencent les actions à effectuer:

Pour `simple_command`:
- `redirections`
- `words`
- `assignments`

Pour `subshell`:
- `redirections`

Les structures correspondantes se trouvent dans `inc/ast.h`

----
## Cas d'utilisation
```c
t_parser	parser;

parser_init(&parser, &tokens);
if (parser_parse(&parser) != NO_ERROR)
{
	parser_print_error(&parser);
	return (-1);
}
parser_shutdown(&parser);
```

----
## Debug
Une fonction de debug est présente pour afficher l'**AST**:
- `ast_debug_print(t_ast *ast)`

Celle-ci est utilisée pour les tests d'intégration (via shellscript)

----
## Tests
Des tests unitaires ont été ajoutés pour le **parser**.
L'**AST** est testé via shellscript.
Une règle a été ajouté au **Makefile** et celle-ci est appelée par la règle **check**.
Néanmoins elle peut être appelée en standalone via `make script`.

**Comment by tmielcza** [comment]
J'ai corrigé quelques coquilles.

Sinon ce serait pas mal de donner la grammaire exacte du parser, c'est à dire celle imposée par le sujet plutôt que celle de POSIX, étant donné que pour le moment le parser ne prend en compte que la première.

**Comment by tmielcza** [comment]
L'interface est differente du lexer (alors que les deux objets ont un fonctionnement tres proche), ce qui est assez deroutant.

**Comment by tmielcza** [comment]
Merge #85
