### ISSUE TITLE
Builtin HELP.

### ISSUE THREAD

**Issue by Otaekek** [itheof/42sh-posix#86]
L'érgonomie du shell est requise dans le projet.
Un builtin HELP qui permettrait de décrire tous les différent raccourcis serait pas mal selon moi.

**Comment by itheof** [comment]
j ecrirai une man page. cc @tmielcza

**Comment by tmielcza** [comment]
Ca va sauter ca je pense.

**Comment by dkrmr** [comment]
Bientot 2 mois. Pas de manpage en vue. Utilité discutable, on dégage pour le moment.
