### ISSUE TITLE
!

### ISSUE THREAD

**Issue by Otaekek** [itheof/42sh-posix#87]
L'une de nos features optionelles impose de recoder le "!" qui est une forme d'expansion.
Etant donner qu'on avait décider de laisser l'expansion de coté, devrait on abandonner ce bonus la OU devrait on implementer une forme basique d'expansion ?
Dans le second cas, comment s'y prendre ?

**Comment by dkrmr** [comment]
Cette expansion s'effectue avant meme la phase de lexing, si on suit la documentation de Bash, dont cette feature est tirée.
Donc je serais pour faire une phase intermédiaire entre l'input et le lexer, **history expansion**. Simple et clair, qu'on pourra retirer ensuite si on le désire car ce n'est pas POSIX.

**Comment by Otaekek** [comment]
https://www.gnu.org/software/bash/manual/html_node/Event-Designators.html#Event-Designators
Doit-on recoder toutes les options pour que ce soit conforme au sujet ?

**Comment by itheof** [comment]
Yep

**Comment by Otaekek** [comment]
![ouais](https://cloud.githubusercontent.com/assets/8776538/21844319/63dfe91a-d7ee-11e6-8dc9-173aa7503bc2.jpeg)

**Comment by dkrmr** [comment]
Mais non, ne te fais pas chier. Personne ne saura comment fonctionne ce truc de toute façon. Autant faire un truc simple et qui couvre les common cases (sachant que ce truc n'est meme pas POSIX).
Le sujet dit: **avec toutes leurs options si elles en ont.**
Comme on a pris `mksh` comme shell de référence, et qu'il n'implémente pas ces features, on dira qu'on a implémenter ce qui sert le plus et c'est tout. Le sujet est assez large pour englober cette interprétation. Donc fait juste ces 4 là:
```
!n Refer to command line n.
!-n Refer to the command n lines back.
!! Refer to the previous command. This is a synonym for ‘!-1’.
!string Refer to the most recent command preceding the current position in the history list starting with string.
```

**Comment by Otaekek** [comment]
Ce raccourci est rendu possible uniquement parce qu'on est sur de ne pas se faire corriger par dkrmr, tvallee et mzapatta :)

**Comment by dkrmr** [comment]
C'est qui `mzapata` ?

**Comment by Otaekek** [comment]
![screen shot 2017-01-13 at 11 51 59 am](https://cloud.githubusercontent.com/assets/8776538/21927643/c8fac862-d986-11e6-9972-b59af113cd9a.png)
https://www.youtube.com/watch?v=bSjjqhQ_99g
Le ! ne faisant pas partie du standart POSIX, on peux l'implementer a peu pres comme on veux.

**Comment by tmielcza** [comment]
Cette issue ne sert plus a rien, le CdC est fait, la review est en cours et c'est bientot merge (si tout se passe bien).
