### ISSUE TITLE
Gestion d'erreur (encore)

### ISSUE THREAD

**Issue by tmielcza** [itheof/42sh-posix#91]
Un rapide coup d'oeil au man d'`access(2)` (par exemple) dévoile que la fonction peut foirer pour toute une chiée de raisons aussi farfelues les unes que les autres.

Plusieurs solutions s'offrent à nous (ouais je perds pas de temps) : 
- On peut recopier toutes les erreurs possibles et imaginables dans notre propre copie du système de gestion d'erreur de la lib standard, comme ça il n'y a plus qu'à recopier errno dans g_errno et appeler ft_perror() au lieu de perror(), comme c'est pratique.
- Pourquoi s'embêter, on peut simplement afficher qu'il y a une erreur quelconque, et à l'utilisateur de faire marcher son imagination. Sympa pour un shell.
- Ou alors on peut utiliser un bon vieux strerror() pour avoir un bout de message clair qu'on contextualise dans une jolie chaine de caractères avant de l'afficher sur la sortie d'erreur.

Comme le suggère mon ton sarcastique sur deux des possibilités, je serais plutôt partisan de la troisième, à voir si on se sent d'éventuellement avoir à argumenter en correction.

Sur le même thème, pour l'instant on n'a pas vraiment décidé de la manière de gérer les erreurs. Il y a bien un petit truc dans la norme concernant les `assert()` que personne n'utilise et un post sur Trello + une implémentation d'un substitut d'errno / perror dans la lib mais pareil, déjà je trouve ça bof, et pour le moment on ne s'en sert pas.

D'ailleurs, pour l'instant on n'affiche jamais de message d'erreur puisqu'il n'y a pas de programme. Mais quand est ce qu'on est censé afficher quelque chose ? Là par exemple je taffe sur la recherche de commande (eh oui, je m'y suis remis après des semaines d'oisiveté !). J'utilise `access()` qui comme dit plus haut se sert d'errno pour exprimer sa détresse le cas échéant. Est-ce que je chie un message d'erreur ? Est ce que je renvoie simplement une valeur et on se débrouille en dessous ? Le problème c'est que plus on remonte dans la stack plus on perd de contexte. Il faudrait pouvoir concaténer le contexte à une string d'erreur globale et l'afficher à la fin, au bon moment (c'est sûrement comme ça qu'ils font d'ailleurs, ça semble assez efficace vu comme ça).

Et puis il y a la distinction entre les erreurs que peut rencontrer notre programme et qui engendrent éventuellement sa fermeture, et les erreurs générées par l'exécution d'une commande.

Bref je suis confus. Peut être que c'est limpide pour tout le monde, ou qu'on en a déjà discuté quelque part, auquel cas faites moi signe que je dégage cette issue, mais sinon il faudrait peut être écrire quelques lignes à ce sujet, après s'être concertés, histoire d'avoir le coeur léger et la conscience tranquille.

XOXOXO

**Comment by dkrmr** [comment]
Tu veux utiliser la fonction `strerror` du système ? C'est un man(3)
Par contre on a accès au tableau qui contient les messages:
```c
#include <stdio.h>

extern const char * const sys_errlist[];
```

Concernant les `assert()`, je plaide coupable, j'ai du mal à chopper le reflexe de les utiliser.
Le substitut d'errno je m'en sert dans le parser perso.

La question des erreurs et des messages d'erreur à afficher devrait être tranché en réunion. D'ailleurs réunion, à quand la prochaine ?

**Comment by tmielcza** [comment]
Super, je ne trouvais pas ledit tableau (pas trop cherché mais quand même). Je vote donc pour qu'on l'utilise, si possible. Et selon comment on traite les erreurs on peut effectivement avoir notre `errno` à nous pour gérer nos erreurs spécifiques au shell, mais pour ça il faut surtout avoir une gestion d'erreurs globalement efficace, récupérer quand il faut la valeur d'`errno`, et forger (😆 ) le message d'erreur qui convient.
