### ISSUE TITLE
[CDC] Module !

### ISSUE THREAD

**Issue by Otaekek** [itheof/42sh-posix#95]
# Resumé
La substitution ! nous viens de bash et est une forme de substitution pre-lexing qui permet d'inserer dans la ligne de commande des commandes rentrés précédemmet dans l'historique.
Etant donnes que le sujet est plutôt open vis-a-vis de la manière de l'implementer, notre implementation ne suivra pas toutes les directives de la doc Bash.

# Charges
- Parser la ligne de commande et extraire les commandes de substitutions ainsi que leurs paramétres.
- Supprimer les commandes de substitutions et insérer les résultats de la substitution.
Les substitutions suivantes seront implémentés:
- !n Refer to command line n.
- !-n Refer to the command n lines back.
- !! Refer to the previous command. This is a synonym for ‘!-1’.
- !string Refer to the most recent command preceding the current position in the history list starting with string.

# Interface
`void history_substitutions(t_string command)`
Cette fonctions sera call apres chaque retour de la phase d'UI.

**Comment by tmielcza** [comment]
C'est merged.

**Comment by tmielcza** [comment]
C'est merged.
