### ISSUE TITLE
echo

### ISSUE THREAD

**Issue by itheof** [itheof/42sh-posix#98]
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html

Je pense implementer les sequences d'echappement et '-n'

**Comment by tmielcza** [comment]
Je pense qu'on peut drop les séquences d'échappement pour le moment, d'autant qu'elles sont pas strictement demandées par POSIX.

**Comment by dkrmr** [comment]
Pas urgent, on verra si on n'a le temps

**Comment by itheof** [comment]
Pour les sequences d'echappement, elles ne sont pas interpretes comme POSIX le demande dans `mksh` (en particulier le `\c`).

**Comment by tmielcza** [comment]
Merge avec #108.
